### ISSUE TITLE
neue UnterputzSchalter werden nicht erkannt

### ISSUE THREAD

**Issue by Whitehawk2000** [ioBroker/ioBroker.mihome#10]
Die neuen Unterputzschalter mit "Neutralleiter" werden von dem Adapter leider nicht erkannt, oder nicht an diesen weitergegeben.
In der MiHomeApp lassen Sie sich jedoch einwandfrei ansprechen.

Hier die DebugAusgabe des Adapters. Lediglich der Gateway und der Funk-Aufputzsschalter werden korrekt in den Adapter übernommen.

`mihome.0   2018-02-11 15:44:03.788   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.86sw2_158d000170ebe7.channel_1 {'val':false,'ack':true,'ts':1518360243784,'q':0,'from':'system.adapter.mihome.0','lc':1518360243784}
mihome.0   2018-02-11 15:44:03.783   debug   data: 158d000170ebe7(86sw2): {'channel_1':false}
mihome.0   2018-02-11 15:44:03.494   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.86sw2_158d000170ebe7.channel_1 {'val':true,'ack':true,'ts':1518360243485,'q':0,'from':'system.adapter.mihome.0','lc':1518360243485}
mihome.0   2018-02-11 15:44:03.493   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.86sw2_158d000170ebe7.channel_1_double {'val':false,'ack':true,'ts':1518360243484,'q':0,'from':'system.adapter.mihome.0','lc':1518359285963}
mihome.0   2018-02-11 15:44:03.487   debug   RAW: {'cmd':'report','model':'86sw2','sid':'158d000170ebe7','short_id':17339,'data':{'channel_1':'click'}}
mihome.0   2018-02-11 15:44:03.486   debug   data: 158d000170ebe7(86sw2): {'channel_1_double':false,'channel_1':true}
mihome.0   2018-02-11 15:43:59.797   debug   RAW: {'cmd':'heartbeat','model':'gateway','sid':'7811dc64dbcd','short_id':'0','token':'RutivcU5r7wRY5NB','data':{'ip':'192.168.178.34'}}
mihome.0   2018-02-11 15:43:49.882   debug   RAW: {'cmd':'heartbeat','model':'gateway','sid':'7811dc64dbcd','short_id':'0','token':'Des37Qmi6bWAow4O','data':{'ip':'192.168.178.34'}}
mihome.0   2018-02-11 15:43:39.845   debug   RAW: {'cmd':'heartbeat','model':'gateway','sid':'7811dc64dbcd','short_id':'0','token':'qH5y3eBHyXFkyI2D','data':{'ip':'192.168.178.34'}}
mihome.0   2018-02-11 15:43:29.918   debug   RAW: {'cmd':'heartbeat','model':'gateway','sid':'7811dc64dbcd','short_id':'0','token':'EUBLpJ8Ghv4T7jn8','data':{'ip':'192.168.178.34'}}
mihome.0   2018-02-11 15:43:19.887   debug   RAW: {'cmd':'heartbeat','model':'gateway','sid':'7811dc64dbcd','short_id':'0','token':'zC29AVjz2NDqKygj','data':{'ip':'192.168.178.34'}}
mihome.0   2018-02-11 15:43:13.939   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.86sw2_158d000170ebe7.percent {'val':85.5,'ack':true,'ts':1518360193901,'q':0,'from':'system.adapter.mihome.0','lc':1518359254738}
mihome.0   2018-02-11 15:43:13.939   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.86sw2_158d000170ebe7.voltage {'val':3.055,'ack':true,'ts':1518360193900,'q':0,'from':'system.adapter.mihome.0','lc':1518359254737}
mihome.0   2018-02-11 15:43:13.938   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.gateway_7811dc64dbcd.rgb {'val':'#000000','ack':true,'ts':1518360193899,'q':0,'from':'system.adapter.mihome.0','lc':1518359097156}
mihome.0   2018-02-11 15:43:13.937   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.gateway_7811dc64dbcd.dimmer {'val':0,'ack':true,'ts':1518360193897,'q':0,'from':'system.adapter.mihome.0','lc':1518359097154}
mihome.0   2018-02-11 15:43:13.937   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.gateway_7811dc64dbcd.on {'val':false,'ack':true,'ts':1518360193895,'q':0,'from':'system.adapter.mihome.0','lc':1518359097152}
mihome.0   2018-02-11 15:43:13.936   debug   redis pmessage io.mihome.0.devices.* io.mihome.0.devices.gateway_7811dc64dbcd.illumination {'val':1265,'ack':true,'ts':1518360193894,'q':0,'from':'system.adapter.mihome.0','lc':1518360193894}
mihome.0   2018-02-11 15:43:13.910   debug   RAW: {'cmd':'read_ack','model':'86sw2','sid':'158d000170ebe7','short_id':17339,'data':{'voltage':3055}}
mihome.0   2018-02-11 15:43:13.910   debug   data: 158d000170ebe7(86sw2): {'voltage':3.055,'percent':85.5}
mihome.0   2018-02-11 15:43:13.909   debug   device: 158d000170ebe7(86sw2)
mihome.0   2018-02-11 15:43:13.909   debug   RAW: {'cmd':'read_ack','model':'gateway','sid':'7811dc64dbcd','short_id':0,'data':{'rgb':0,'illumination':1265,'proto_version':'1.0.9'}}
mihome.0   2018-02-11 15:43:13.908   debug   data: 7811dc64dbcd(gateway): {'illumination':1265,'on':false,'dimmer':0,'rgb':'#000000'}
mihome.0   2018-02-11 15:43:13.864   debug   RAW: {'cmd':'get_id_list_ack','sid':'7811dc64dbcd','token':'d2FX41x6Q6Fyxl8M','data':['158d0001f247d5','158d000170ebe7']}
mihome.0   2018-02-11 15:43:13.466   debug   RAW: {'cmd':'iam','port':'9898','sid':'7811dc64dbcd','model':'gateway','ip':'192.168.178.34'}
mihome.0   2018-02-11 15:43:13.464   debug   device: 7811dc64dbcd(gateway)
mihome.0   2018-02-11 15:43:13.286   info   starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.mihome, node: v6.12.2
mihome.0   2018-02-11 15:43:09.029   info   terminating`

Wo kann das Problem dabei liegen und wie kann ich dabei helfen dies zu lösen?

**Comment by GermanBluefox** [comment]
Man kann 2 Geräte sehen: ['158d0001f247d5','158d000170ebe7']
Aber 158d0001f247d5 meldet sich nie. Nur  158d000170ebe7 als 86sw2.
Wenn 158d0001f247d5 schweigt, dann wie kann man den erkennen?

**Comment by Whitehawk2000** [comment]
Ich habe von Adaptern in ioBroker leider zu wenig Ahnung als dass ich da eine Antwort darauf hätte. 
Da die Geräte-id an den Adapter weitergeleitet wird, bin ich davon ausgegangen, dass der Adapter einfach nur nichts mit dem Gerät anfangen kann, da evtl. noch nicht eingepflegt.
Dass der Schalter sich auch nochmal explizit bei dem Adapter melden muss habe ich ausgeschlossen, da nach meinem Verständnis der Adapter nur die Daten vom Gateway ausliest und dann weiterverarbeitet.

In der MiApp funktioniert der Schalter ja wunderbar und ich kann ihn mit anderen Schaltern verknüpfen etc.

**Comment by GermanBluefox** [comment]
Wenn Sensor sich nicht meldet, ich kann NICHTS machen.

**Comment by Whitehawk2000** [comment]
Wie es der Zufall will meldet sich der Schalter jetzt in ioBroker nach einem neuen Firmwareupdate des Gateways:

mihome.0 | 2018-03-04 16:17:34.849 | warn | Could not add new sensor: Type "ctrl_ln2.aq1" is not valid, use one of Hub::sensorTypes
-- | -- | -- | --

Liege ich jetzt richtig in der Annahme, dass in der hub.js nur noch die Dateiendung ".aq1" zu "ctrl_ln2" hinzugefügt werden muss?

**Comment by GermanBluefox** [comment]
Jetzt ist alles richtig:) und ich kann implementieren.

4 мар. 2018 г. 16:23 пользователь "Whitehawk2000" <notifications@github.com>
написал:

**Comment by GermanBluefox** [comment]
PLease test 1.0.5

**Comment by Whitehawk2000** [comment]
Works great! Thank you very much!!! :-)

**Comment by GermanBluefox** [comment]
So close please the issue.

**Comment by lospiratos** [comment]
Wenn man im BlocklyScript das Objekt deceive/Gateway/ mid oder rgb ansteuern will, so muss man vorher ein Leerzeichen vor dem Wert vergeben. Z.B. eine Farbe auf dem Gateway schalten lassen mit dem HEX Farbcode #0061ff so muss davor ein Leerzeichen vor den HEX Wert setzen, sonst bekommt man die rote Farbe statt blau. Will man irgendeinen Ton wiedergeben mit einer Zahl so wird eine Sirene abgespielt statt dem richtigen Ton, ausser man setzt ein Leerzeichen vor die Zahl. (Nur zur Info: die Selbst angelegten Töne in der MiHome App lassen sich beginnend mit der Zahl 10000 im IOBroker abspielen.
