### ISSUE TITLE
Missing states for NatGas-Detector and Smoke-Detector

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.mihome#100]
The Natural Gas Detector and the Smoke Detector are accepting changes on their sensitivity.
On both the setable sensetivity state is missing...

If you use the zigbee-adapter, at least for the natural gas detector it is setable.

**Comment by Apollon77** [comment]
Please set adapter to debug loglevel and provide logs please

**Comment by nob0dy80** [comment]
@Apollon77 

repairing needed to fetch the missing states?
you need to give me more informations what to do to get the informations in log you want.
