### ISSUE TITLE
Gateway Control via ioBroker not possible

### ISSUE THREAD

**Issue by adcrafter27** [ioBroker/ioBroker.mihome#102]
Hello.
If i want to switch on the led from the gateway via the iobroker or make another change, 
i get the error and the adapter restarts and no change has been made.
Everything can be controlled via the Handy app

Version 1.2.8

![fehler_mihome](https://user-images.githubusercontent.com/15692264/72760934-a8da2780-3bda-11ea-83ec-53b5e7bf6f0a.png)

**Comment by Apollon77** [comment]
which nodejs version do you use?

**Comment by adcrafter27** [comment]
v8.17.0

**Comment by Ilovegym66** [comment]
In your Error Log is the Message "invalid Key lenght" Check the Key, please.

**Comment by adcrafter27** [comment]
Thanks that was the problem, apparently the key had changed during an update
