### ISSUE TITLE
Support for Xiaomi Mijia Multi-Mode Smarthome Gateway

### ISSUE THREAD

**Issue by hilde0407** [ioBroker/ioBroker.mihome#103]
Is it possible to add support for the new gateway?
https://de.gearbest.com/smart-home-controls/pp_009832470551.html

Thank You

Volker

**Comment by Ingo1977** [comment]
Any news on this? I made it to extract the token from the device but after entering all the data into the latest MIHome adapter/instance, it still shows a yellow bubble instead of getting green :-( What needs to be done to make it work? I can see in a lot of other forums that this new gateway is getting more attractive... Thanks.

**Comment by Diginix** [comment]
Sure that the port is open?
I've read information across the net that on the newer gateway (guess v3) the port can only be opened by soldering something inside.

**Comment by Ingo1977** [comment]
To be honest, I would be able to solder it but how to open the case of the gateway and what needs to be soldered afterwards?

**Comment by Diginix** [comment]
I have no more details. Please search yourself. But this is no iobroker topic or issue of the adapter anymore.

**Comment by pixelsophie** [comment]
> Is it possible to add support for the new gateway?
> https://de.gearbest.com/smart-home-controls/pp_009832470551.html
> 
> Thank You
> 
> Volker

Gibt es mittlerweile eine Lösung oder einen Workaround?

**Comment by kruemelg** [comment]
Think there are a lot of people interested in. I connected my Flower Care Sensors to this Gateway via Bluetooth Mesh.... and now the problem with the distance of the Bluetooth is nearly solved.... but how to get this Gateway in to ioBroker? :-(
