### ISSUE TITLE
Keine Verbindung zum Gateway im Docker

### ISSUE THREAD

**Issue by githubwesseln** [ioBroker/ioBroker.mihome#104]
MiHome Adapter läuft in normaler Installation, aber beim ioBroker im Docker bekommt er keine Verbindung mehr, gibt es eine Lösung hierfür ?

**Comment by sirvancobra** [comment]
Same error. As updated iobroker to docker, apapter does not working anymore. Any new infos?

**Comment by Apollon77** [comment]
ANd so when everything works and not ion Docker it is a problem of the adapter? Sure? ;-)

The adapter uses UDP ... so make sure the UDP messages get somehow in and out of your docker containters .... Nothing where the adapter can do anything

**Comment by sirvancobra** [comment]
Normally i would agree but in this case I compose the 9898  port via UDP and test it with netcat (pi->gateway, container->gateway) and with portqry (notebook->pi, notebook->gateway). All ports are opened. But the container (netstat) shows udp is opened but no one is listening.
Do you have any other advices what it could be?

I'm using node12 and lumi.gateway.v3

**Comment by Apollon77** [comment]
Then provide logs please. Any error there?

**Comment by sirvancobra** [comment]
Can't see any errors:
mihome.0 | 2020-06-18 20:11:58.008 | info | (16260) Change connection status: false
-- | -- | -- | --
mihome.0 | 2020-06-18 20:11:57.921 | info | (16260) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.mihome, node: v12.18.0, js-controller: 3.1.5
mihome.0 | 2020-06-18 20:11:53.856 | info | (14307) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome.0 | 2020-06-18 20:11:53.854 | info | (14307) terminating
mihome.0 | 2020-06-18 20:11:53.851 | info | (14307) Got terminate signal TERMINATE_YOURSELF
mihome.0 | 2020-06-18 19:46:38.347 | info | (14307) Change connection status: false
mihome.0 | 2020-06-18 19:46:38.269 | info | (14307) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.mihome, node: v12.18.0, js-controller: 3.1.5
mihome.0 | 2020-06-18 19:46:36.025 | info | (13601) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome.0 | 2020-06-18 19:46:36.024 | info | (13601) terminating
mihome.0 | 2020-06-18 19:46:36.022 | info | (13601) Got terminate signal TERMINATE_YOURSELF
mihome.0 | 2020-06-18 19:36:57.837 | info | (13601) Change connection status: false
mihome.0 | 2020-06-18 19:36:57.761 | info | (13601) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.mihome, node: v12.18.0, js-controller: 3.1.5
mihome.0 | 2020-06-18 19:36:53.592 | info | (562) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mihome.0 | 2020-06-18 19:36:53.591 | info | (562) terminating
mihome.0 | 2020-06-18 19:36:53.586 | info | (562) Got terminate signal TERMINATE_YOURSELF

![image](https://user-images.githubusercontent.com/30898006/85056925-552b3480-b1a0-11ea-991c-32587ab7a6d3.png)

![image](https://user-images.githubusercontent.com/30898006/85057489-18ac0880-b1a1-11ea-996e-c6354ee1b6ca.png)

**Comment by sirvancobra** [comment]
After a lot of work it's running now. You were right, the problem is iobroker in docker. The container opened udp ports but can bind the listener. Unfortunately the iobroker container can't be run in host mode so I had to create a macvlan.

sudo docker network create -d macvlan --subnet=192.168.178.81/24 --gateway=192.168.178.1 -o parent=eth0 pub_net
sudo ip link add mac0 link eth0 type macvlan mode bridge
sudo ip addr add 192.168.178.81/24 dev mac0
sudo ifconfig mac0 up

And then give the container a free ip address from pool. Now mihome and my shelly adapter are working. I hope it will helps others too.
