### ISSUE TITLE
Xiaomi WSDCGQ11LM: falsche Einheit für Luftdruck

### ISSUE THREAD

**Issue by thatso** [ioBroker/ioBroker.mihome#105]
Bei meinem Xiaomi WSDCGQ11LM Sensor am Mi Gateway V2 zeigt mir der aktuelle mihome Gateway Adapter V1.3.0 für den Luftdruck z. B. 930.5 Pa, während die MiHome App 93.0 kPa anzeigt.
Ich denke, die Einheit in ioBroker ist falsch und sollte **h**Pa lauten.

**Comment by Diginix** [comment]
You are right. I have changed it in the repo and made a pull request.
