### ISSUE TITLE
Xiaomi WSDCGQ11LM: Höhenkorrektur?

### ISSUE THREAD

**Issue by thatso** [ioBroker/ioBroker.mihome#110]
Neben der falschen Einheit für den Luftdruck #106 vermisse ich eine Höhenkorrektur. Auch in der MiHome App finde ich keine Möglichkeit, die Höhe des Messortes über dem Meeresspiegel anzugeben. Die angezeigten Werte für den Luftdruck sind somit immer deutlich zu niedrig.
Wäre schön, wenn man z. B. auf der Konfigurationsseite des Adapters einen Offset angeben könnte.

**Comment by Diginix** [comment]
Der gemessene Luftdruck ist doch schon der vom Ort und dessen Höhe über NN. Wieso willst du dafür eine Korrektur? Normalerweise nutzt man den Luftdruck um die Höhe zu berechnen und nicht anders rum. Ich wohne auf 500 müNN und bei mir stimmt der Wert vom Aqara T/H/P Sensor bis auf 2 hPa genau und das über das gesamte Jahr. Welchen Sensor hast du und wieso sind die Werte zu niedrig?

**Comment by thatso** [comment]
Die Werte eines Luftdrucksensors müssen mit der Höhe korreliert werden, weil sie sonst falsch sind. Welchen Aqara Sensor ich habe, steht in der Überschrift.
Zum Vergleich: eine lokale, öffentlich abrufbare Wetterstation stimmt aktuell mit einem höhenkorrigierten BME280 auf 1 hPa überein, wohingegen der Aqara satte 68 hPa zu wenig anzeigt.

**Comment by Diginix** [comment]
Die 2 hPa Abweichung bei mir sind auch verglichen zu einer Wetterstation die Luftlinie 2 km entfernt ist. Und beide Werte logge ich schon mehr als 12 Monate. Immer die gleiche minimal Abweichung.
Die Ausreißer zu Null waren vom Xiaomi bevor ich das im Code abgefangen habe.

![image](https://user-images.githubusercontent.com/39678667/78401402-f7536b80-75f8-11ea-87c3-8056fb19df2c.png)

**Comment by thatso** [comment]
Das ist schön für Dich ... hilft aber hier nicht weiter. Mag sein, daß mein Sensor eine Gurke ist. Vielleicht ist aber auch Deiner grottig und zeigt konstant 70 hPa zu viel an, so daß die Werte zufällig bei Dir dadurch stimmig aussehen.

**Comment by Diginix** [comment]
Das ist ja unlogisch, dass ein korrekt anzeigender Sensor grottig sein soll und zu viel anzeigt, aber doch richtig. Nun gut. Ich kenne mich mit diesen Details nicht aus. Mir reicht der relative Trend des Luftdruckes und die absoluten Werte sind belanglos. Ich will keinen Fallschirm damit notöffnen ;-)

**Comment by thatso** [comment]
BTW: wenn man sich mal bei einschlägigen Projekten zum Thema Home Automation und Sensoren umsieht, haben die durchwegs alle eine Korrekturmöglichkeit für Temperatur/Luftfeuchtigkeit/Luftdruckwerte vorgesehen - eben weil Sensoren einfach systematische Messfehler haben.

**Comment by Diginix** [comment]
Klar ist das sinnvoll. Aber das darf dann nicht in den Adapter, also nicht nur ein Wert in der Instsanz. Es muss ja pro Sensor gepflegt werden und dann ist es manchmal auch kein linearer Offset. Das macht es nicht einfacher.
Man müsste also überlegen ob und wo man in ioBroker Sensorkorrekturfaktoren im System unterbringen könnte.

**Comment by thatso** [comment]
Yup - jetzt sind wir beieinander.
Die Konfigurationsdatei-lastigen Projekte haben es da einfacher, die schreiben einfach den Offset in die zugehörige Datei. Genau deshalb habe ich aber ioBroker für mich ausgewählt: kein Bock auf Textadventure.
Die Holzhamer-Methode wäre vermutlich, einfach den Datenpunkt im Rohformat zu editieren. Das könnte man dann aber auch als Spalte im GUI umsetzen. Ich denke da an ein Eingabefeld für eine Rechenformel. Meist sind es ja nur feste Werte zum Aufaddieren oder Subtrahieren.

**Comment by thatso** [comment]
Übrigens wird [bei HA](https://community.home-assistant.io/t/xiaomi-aqara-new-temperature-humidity-and-pressure-sensor-sea-level-pressure/95034) anschaulich erklärt, warum die Aqara Luftdruckwerte ohne Korrektur ziemlich nutzlos sind.
Wenn ich zum Vergleich bei meinem BME280 die Höhenkorrektur entferne, lande ich bei ziemlich genau den Werten, die der Aqara liefert.
