### ISSUE TITLE
false positives on mijia and aqara pir sensors

### ISSUE THREAD

**Issue by vladitep** [ioBroker/ioBroker.mihome#12]
i have 5 pir sensors, 2 of them have work in my system and 3 - got connected to gateway and bring back into their boxes to wait when they have been needed.
And i have false positives on all of them, sometimes all work well for long time, but sometimes they start triggered for few times a day and even hour! 
At MiHome app no any false positives and nothing in mihome log, so i thing sensors work correct

**Comment by GermanBluefox** [comment]
Do you have some logs?

vladitep <notifications@github.com> schrieb am Mo., 19. März 2018, 22:08:

**Comment by vladitep** [comment]
mihome.0 | 2018-03-20 11:51:48.856 | debug | RAW: {"cmd":"heartbeat","model":"motion","sid":"158d00016c035f","short_id":44079,"data":{"voltage":3055,"status":"motion"}}
-- | -- | -- | --
mihome.0 | 2018-03-20 11:51:48.853 | debug | data: 158d00016c035f(motion): {"voltage":3.055,"percent":85.5,"state":true,"no_motion":0}

after that i have false triggered on the second sensor:

mihome.0 | 2018-03-20 11:54:45.713 | debug | RAW: {"cmd":"heartbeat","model":"sensor_motion.aq2","sid":"158d00016c3b46","short_id":804,"data":{"voltage":3055,"status":"motion","lux":"945"}}
-- | -- | -- | --
mihome.0 | 2018-03-20 11:54:45.713 | debug | data: 158d00016c3b46(sensor_motion.aq2): {"voltage":3.055,"percent":85.5,"state":true,"no_motion":0,"lux":945}


sensors always have false positives together - first and then after couple seconds another

**Comment by GermanBluefox** [comment]
If the sensor says: motion.... How is adapter is guilty on that?

**Comment by vladitep** [comment]
sensors say nothing, in log at MiHome app - no motions at this time
And, i noticed it just now - "no motion" state show a real time of motion (yesterday instead of today at "motion" state). If it not bug,  this is not possible, right?

**Comment by vladitep** [comment]
![screen](https://user-images.githubusercontent.com/24714809/37660682-ffe7837a-2c63-11e8-8b39-0c7e03c9a3a7.jpg)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/37660773-795285f4-2c53-11e8-9e1f-42ca6db2e8b7.png)
This is indication for motion for sensor 158d00016c3b46.

**Comment by GermanBluefox** [comment]
This is bug in Gateway. RAW it is that, what adapter receives from gateway. If gateway says "motion", how can I distinguish between wrong and right?

**Comment by vladitep** [comment]
But in the MiHome application everything is fine, no false positives. Gateway sends different data to the MiHome application and adapter?
Maybe adapter incorrectly interpreted received data, and status "motion" by itself its not a motion but something like a heartbeat, and for motion is necessary to check "last motion" state together with "motion"?

**Comment by GermanBluefox** [comment]
Is the problem still actual?

**Comment by grdminer** [comment]
I'm not sure but maybe its related to the part "cmd":"heartbeat" in RAW command. Maybe I'm wrong but this is not an update but just a regular hearbeat message as changes are send with "cmd":"report". I only own the old version and these seem to send no status information in the hearbeat message, just the voltage information.

* mihome.0	2018-06-01 21:02:41.388	debug	RAW: {"cmd":"report","model":"motion","sid":"...bb4","short_id":...,"data":{"no_motion":"120"}}
* mihome.0	2018-06-01 21:01:25.807	debug	RAW: {"cmd":"heartbeat","model":"motion","sid":"...5f0","short_id":...,"data":{"voltage":3015}}

I can see that the second message leads to an update of the voltage state of this device so it might lead to false positives in case the status is in the heartbeat message like it is above.

BTW the heartbeat messages are sent more or less frequently by all my mihome devices (Temperature, Door/Window, Gateways, Leak, Motion, Buttons and so on).

**Comment by GermanBluefox** [comment]
Can't understand you well. What does it mean: false positives
May be in deutsch

пт, 1 июн. 2018 г., 21:16 grdminer <notifications@github.com>:

**Comment by grdminer** [comment]
Hallo GermanBluefox,

ich denke die false positives könnten daher kommen das nicht nur messages vom Typ cmd:report verarbeitet werden sondern auch die vom Typ cmd:heartbeat. Bei vladitep sind in der Heartbeat Nachricht Statusinformationen enthalten, in diesem Fall "motion". Falls diese verarbeitet werden wie eine Statusmeldung "cmd:report" führt das zu einem falschen Ergebnis und dem Ändern des Status in iobroker. Ich habe hier >30 Xiaomi Sensoren im Einsatz welche alle in unterschiedlichen Zyklen Heartbeat Nachrichten schicken allerdings ist in keiner Heartbeat Nachricht der jeweilige Status (motion, open etc) enthalten sondern jeweils nur die voltage. Ich kann aber sehen das ein Heartbeat zum Update des State führt und das wird vermutlich bei alle Informationen passieren die im Heartbeat enthalten sind. Aus meiner Sicht ist ein Heartbeat kein echtes Statusupdate sondern lediglich ein Lebenszeichen und sollte vielleicht nicht dazu führen das states aktualisiert werden sondern eher eine timestamp (zB lastSeen) setzen.

Siehe auch: 
- https://louiszl.gitbooks.io/lumi-gateway-local-api/device_heartbeat.html
- https://www.docdroid.net/hIVlw6c/gatewaylancommunication.pdf#page=3

Viele Grüße

**Comment by GermanBluefox** [comment]
Sehr ausführliche Erklärung. Danke.

**Comment by GermanBluefox** [comment]
So I modified Alarm, DoorSensor, MotionSensor and WaterSensor to not analyse the alarms/motion/events from heartbeats, but the voltage and lux will be still analysed.
What about lux in MotionSensor? Is the information OK inheartbeat?

What about Temperature and Pluf and Buttons? Is the info OK in heartbeats?

**Comment by grdminer** [comment]
Hallo GermanBluefox,

Vielen Dank, ich denke das schließt einige Fehlerquellen aus. Leider habe ich keine genauen Informationen dazu gefunden ob der Heartbeat aktuelle Werte oder Werte aus der Vergangenheit enthält bzw. welche Werte überhaupt (die alten Motion Sensoren enthalten bei mir z.B. im Heartbeat keinen Status, ich habe aber leider keine der neuen Serie).  Ich werde mal einige Logs auswerten vielleicht lässt sich daraus etwas ableiten. Vielleicht meldet sich ja auch der Fragensteller nochmal.

Viele Grüße

**Comment by grdminer** [comment]
Nachtrag: ich habe die letzten Stunden mihome im debug laufen lassen und jeweils ein Gerät pro Typ ausgewertet. 

Folgende Geräte haben, neben dem Batterielevel, Statusdaten im Heartbeat (bei mir sind diese gleich zu den zuletzt gelieferten Werten): 
- magnet (status)
- sensor_magnet.aq2 (status)
- sensor_ht (temperature,humidity) 
- weather.v1 (temperature,humidity,pressure). 

Folgende Geräte liefern nur den Batterielevel:
- 86sw2
- motion
- switch

Der sensor_wleak.aq1 hat in der Zeit (ca. 5h) keinen Heartbeat geliefert. Dieser scheint nur beim Neustart per "cmd":"get_id_list_ack" Daten zu liefern.

Bei mir sind im Heartbeat (wenn vorhanden) immer die aktuellsten Werte drin daher scheint es auch keine negativen Auswirkungen zu haben. Eventuelle verhalten sie andere Sensoren aber anders, man sieht das ja schon bei den paar die ich habe.

Hoffe das hilft.

Viele Grüße
