### ISSUE TITLE
Since V1.3.2 Switch SW2 don't work anymore

### ISSUE THREAD

**Issue by Kumskaka** [ioBroker/ioBroker.mihome#122]
Since I update to Version 1.3.2 the SW2 Switch get the adapter instance to shutdown and restart.
I get the follow Error message in the log.

mihome.0 | 2020-08-29 03:41:15.861 | error | at UDP.onMessage [as onmessage] (dgram.js:910:8)
-- | -- | -- | --
mihome.0 | 2020-08-29 03:41:15.861 | error | at Socket.emit (events.js:315:20)
mihome.0 | 2020-08-29 03:41:15.861 | error | at Hub.onMessage (/opt/iobroker/node_modules/iobroker.mihome/lib/Hub.js:211:24)
mihome.0 | 2020-08-29 03:41:15.861 | error | at WallButtons.onMessage (/opt/iobroker/node_modules/iobroker.mihome/lib/Sensors/WallButtons.js:93:22)
mihome.0 | 2020-08-29 03:41:15.861 | error | at Hub.emit (events.js:315:20)
mihome.0 | 2020-08-29 03:41:15.861 | error | at Hub.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome/main.js:339:13)
mihome.0 | 2020-08-29 03:41:15.861 | error | at updateStates (/opt/iobroker/node_modules/iobroker.mihome/main.js:115:46)
mihome.0 | 2020-08-29 03:41:15.861 | error | (120640) TypeError: Cannot read property 'common' of undefined
mihome.0 | 2020-08-29 03:41:15.861 | error | (120640) uncaught exception: Cannot read property 'common' of undefined

I downgrade to V1.3.0 and the error is gone.

**Comment by GermanBluefox** [comment]
Fixed with the next version
