### ISSUE TITLE
Datenpunkt ob Verbindung zu Sensor noch besteht

### ISSUE THREAD

**Issue by flisse** [ioBroker/ioBroker.mihome#126]
Hallo,
ist es möglich, einen Datenpunkt bei den Sensoren einzubinden, der einem sagt, ob der entsprechende Sensor überhaupt noch verbunden ist? Ich hatte aktuelle 2 Sensoren, die ihre Verbindung zum Gateway verloren haben, was ich nur durch Zufall mitbekommen habe. Mein Plan ist jetzt, mir eine Überwachung in IO-Broker zu bauen, mit der ich das direkt mitbekomme.

**Comment by Diginix** [comment]
Das Gateway liefert dazu keine Infos und die Sensoren haben recht unterschiedliche Antwortzeiten.
Es gibt keine allg. Logik mit der sich das einfach erkennen lässt.
Bei meinen Temp.sensoren prüfe ich ob sich die Temp. über 4h nicht geändert hat. Falls nicht, gehe ich davon aus dass was nicht stimmt.
Die Türsensoren zB senden aber nur bei Statuswechsel. Wenn man eine Tür aber 1 Woche nicht öffnet/schließt, dann heißt es nicht, dass er offline ist. Die Sensor Batterie lasse ich mir bei kleiner 30 % melden. Manche Sensoren laufen bis 2,655 Volt. Andere haben bei 2,8 V schon nicht mehr gearbeitet.

Du kommst also nicht um eigene Skripte mit spezifischen Regeln herum.
