### ISSUE TITLE
Neues Device hinzufügen

### ISSUE THREAD

**Issue by nicox** [ioBroker/ioBroker.mihome#127]
Ich habe einen neuen "Aqara Door and Window Sensor3" 
Dieser Sensor ist mit dem Gateway verbunden, aber leider wird der Sensor im iobroker nicht angezeigt, wie kann ich vorgehen um das Deivce anzulegen?

Vielen Dank,
Nico

**Comment by Ilovegym66** [comment]
hast du n link zu dem? Kenn nur den Xiaomi und den Aqara. 
Ansonsten mal die Instanz stoppen und neu starten, dauert manchmal n bisschen. 
Was steht im Logfile ? ( auf debug stellen )

**Comment by nicox** [comment]
Auf debug hab ich noch nicht gestellt, wie kann ich das?
im tcpdump kommt folgendes daher was ich noch nicht im iobroker als Objekt habe:
{"cmd":"heartbeat","model":"sensor_magnet.aq2","sid":"158d00054cd378","short_id":60772,"data":"{\"voltage\":3095,\"status\":\"close\"}"}
Ich weiß nicht warum das nicht hinzugefügt wird, das model ist ja klar im Code vorhanden.

**Comment by Diginix** [comment]
Meine eckigen Aqara Door Sensoren laufen auch als Modell "sensor_magnet.aq2" seit Monaten in ioBroker mit dem mihome Adapter.
@nicox Ein neuerer Typ "Sensor3" ist mir nicht bekannt. Sehen deine noch anders als die marküblichen aus?
Falls nicht, müssen die ganz normal funktionieren ohne dass etwas am Adapter angepasst werden muss.

**Comment by nicox** [comment]
Ich vermute mittlerweile auch das die Sensor3 Angabe nur eine Benennung in der Xiaomi App ist.

Aus irgendeinem Grund wird jedoch das Objekt nicht hinzugefügt.
mihome.0	2020-10-25 11:10:48.785	debug	(21910) RAW: {"cmd":"report","model":"sensor_magnet.aq2","sid":"158d00054cd378","short_id":60772,"data":{"status":"close"}}
mihome.0	2020-10-25 11:10:48.785	debug	(21910) data: 158d00054cd378(magnet): {"state":false}
mihome.0	2020-10-25 11:10:46.380	debug	(21910) RAW: {"cmd":"report","model":"sensor_magnet.aq2","sid":"158d00054cd378","short_id":60772,"data":{"status":"open"}}
mihome.0	2020-10-25 11:10:46.380	debug	(21910) data: 158d00054cd378(magnet): {"state":true}

Was läuft hier schief?

**Comment by Diginix** [comment]
Für sachdienliche Hinweise müsstest du erstmal die üblichen Infos für ein Issue nennen:
Plattform?
JS Controller?
Node?
NPM?
Adapter Ver?

Adapter gestoppt und neu gestartet?
System mal neu gestartet?
Sensor in mihome App sauber gekoppelt?
Was passiert wenn du den Button vom Sensor drückst?
Admin Objektliste komplett neu geladen durch Browser Refresh oder das Reload Icon in der Objektliste?

**Comment by nicox** [comment]
Vielen Dank für die vielen Tipps.
Zuerst, das Objekt ist jetzt verfügbar.
Was funktioniert hat war ein upgrade von Node.js v10.22.0 auf Node.js v10.22.1

Ich habe vorher versucht das Betriebssystem neu zu starten (ein lxc Container)    und auch von einen 2. PC und anderen Browsern das Admin Interface zu starten, das half alles nichts
js-controller: 3.1.6
Platform: Debian Linux 10
NPM 6.14.6
Adapter Version: 1.3.0

Vielen Dank!

lg
NIco

**Comment by Diginix** [comment]
Ok, auch gut. Ansonsten wäre noch Adapter Ver. 1.3.5 aus dem latest Repo ein Versuch gewesen. Aber wenn es mit der stable nun läuft...
