### ISSUE TITLE
Wireless Switch Double Klick dont work

### ISSUE THREAD

**Issue by marcf2212** [ioBroker/ioBroker.mihome#13]
Hello, when i klick once, the single value, and the double updates to false. And the same happens when i klick double. I have the Single Aqara Wireless Switch.

**Comment by GermanBluefox** [comment]
Should it work? Is there any datapoint for that?

2018-04-17 20:47 GMT+02:00 marcf2212 <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Do you have logs? Debug level.

ср, 18 апр. 2018 г., 0:21 marcf2212 <notifications@github.com>:

**Comment by marcf2212** [comment]
Sorry, but how can I see the logs?

**Comment by marcf2212** [comment]
?

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.docs/blob/master/faq/003_Admin/006-de-how%20to%20enable%20debug%20logs.md

**Comment by marcf2212** [comment]
When i click once:
`
mihome.0 | 2018-05-10 19:58:04.663 | debug | data: 158d000171019d(86sw1): {"channel_0":false}
-- | -- | -- | --
mihome.0 | 2018-05-10 19:58:04.498 | debug | RAW: {"cmd":"report","model":"86sw1","sid":"158d000171019d","short_id":21649,"data":{"channel_0":"click"}}
mihome.0 | 2018-05-10 19:58:04.492 | debug | data: 158d000171019d(86sw1): {"channel_0_double":false,"channel_0":true}
`
When i click double:
`

mihome.0 | 2018-05-10 19:58:07.512 | debug | data: 158d000171019d(86sw1): {"channel_0":false}
-- | -- | -- | --
mihome.0 | 2018-05-10 19:58:07.326 | debug | data: 158d000171019d(86sw1): {"channel_0":false}
mihome.0 | 2018-05-10 19:58:07.246 | debug | RAW: {"cmd":"report","model":"86sw1","sid":"158d000171019d","short_id":21649,"data":{"channel_0":"click"}}
mihome.0 | 2018-05-10 19:58:07.241 | debug | data: 158d000171019d(86sw1): {"channel_0_double":false,"channel_0":true}
mihome.0 | 2018-05-10 19:58:07.036 | debug | RAW: {"cmd":"report","model":"86sw1","sid":"158d000171019d","short_id":21649,"data":{"channel_0":"click"}}
mihome.0 | 2018-05-10 19:58:07.030 | debug | data: 158d000171019d(86sw1): {"channel_0_double":false,"channel_0":true}


`

**Comment by marcf2212** [comment]
When i click once:

`

mihome.0 | 2018-05-10 20:00:16.665 | debug | data: 158d000171019d(86sw1): {"channel_0":false}
-- | -- | -- | --
mihome.0 | 2018-05-10 20:00:16.503 | debug | RAW: {"cmd":"report","model":"86sw1","sid":"158d000171019d","short_id":21649,"data":{"channel_0":"click"}}
mihome.0 | 2018-05-10 20:00:16.468 | debug | data: 158d000171019d(86sw1): {"channel_0_double":false,"channel_0":true}

`

When i click double:

`

mihome.0 | 2018-05-10 20:01:22.114 | debug | data: 158d000171019d(86sw1): {"channel_0":false}
-- | -- | -- | --
mihome.0 | 2018-05-10 20:01:22.006 | debug | data: 158d000171019d(86sw1): {"channel_0":false}
mihome.0 | 2018-05-10 20:01:22.005 | debug | RAW: {"cmd":"report","model":"86sw1","sid":"158d000171019d","short_id":21649,"data":{"channel_0":"click"}}
mihome.0 | 2018-05-10 20:01:21.999 | debug | data: 158d000171019d(86sw1): {"channel_0_double":false,"channel_0":true}
mihome.0 | 2018-05-10 20:01:21.644 | debug | RAW: {"cmd":"report","model":"86sw1","sid":"158d000171019d","short_id":21649,"data":{"channel_0":"click"}}
mihome.0 | 2018-05-10 20:01:21.639 | debug | data: 158d000171019d(86sw1): {"channel_0_double":false,"channel_0":true}

`

**Comment by GermanBluefox** [comment]
I cannot see any double clicks there. As you can see only two click events have been received with interval of 360 ms.
The event must be not 'click', but 'double_click' and there is no such here.

**Comment by marcf2212** [comment]
Hello. I have no misconfiguration.
Thats just what i meaned. The double click value dont changes when i click double.
It just recieves two one clicks.
And how you see on my screenshot there is a value for that.

**Comment by GermanBluefox** [comment]
I see only "channel_0_double":false," and that means: no double click.

вт, 5 июн. 2018 г., 4:35 marcf2212 <notifications@github.com>:

**Comment by marcf2212** [comment]
Thats what i mean. When i click double on the switch iobroker recieves two one clicks and the value of double click switches to false.

**Comment by GermanBluefox** [comment]
You wrote it right. Iobroker does not receive double click event, because
no one sends it.

ср, 6 июн. 2018 г., 5:06 marcf2212 <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Because Gateway does not send such event. ioBroker cannot do anything with
that.

пт, 20 июл. 2018 г. в 23:27, baerengraben <notifications@github.com>:

**Comment by baerengraben** [comment]
The DoubleClick is shown up on the MiHomeApp. So, my conlcusion is, that the logic (if CoubleClick or not) must be implemented not on the Switch itself but on the "higher Software-Stack". - Even when it's not the "clean way" to do this. Do you agree with that?

If an implementation of the "DoubleClick"-Logic via Adapter is not possible, do you see any chance to implement this elsewhere (maybe scripting)?

**Comment by SchumyHao** [comment]
It seems double click is removed from mijia app too.
Maybe this is not a issue caused by this adapter
