### ISSUE TITLE
Kann Aqara D1 Double Rocker Switch nicht verbinden

### ISSUE THREAD

**Issue by kubakuhn** [ioBroker/ioBroker.mihome#132]
Hi,

ich habe mir 2 neue Double Rocker D1 Switches bestellt. 
https://www.banggood.com/de/Aqara-D1-1-Gang-or-2-Gang-ZigBee-Smart-Wireless-Switch-APP-Remote-Control-Timer-Work-with-APP-HomeKit-p-1644321.html?rmmds=myorder&cur_warehouse=CN&ID=6265279

Diese lassen sich auch Problemlos mit der Xiaomi App Verbinden doch im 
ioBroker erhalte ich immer Warnungen und keines der Geräte erscheint.

mihome.0 | 2020-12-11 00:19:48.150 | warn | **(31964) Could not add new sensor: Type "remote.b286acn02" is not valid, use one of Hub::sensorTypes**

Adapter Version ist **1.3.5**
Gateway ist auf Version **1.4.1_176.0220**
also alles aktuell.

Kann mir jemand helfen und sagen was ich tun kann? Oder ist es ein Bug mit den Geräten und dem Adapter?

LG

**Comment by Diginix** [comment]
remote.b286acn02 wird bis einschließlich Adapter Ver. 1.3.6 noch nicht unterstützt.
Stell die Instanz auf Loglevel Debug und drück alles was es an Events bei diesem Schalter gibt einmal durch und poste hier dann das Debuglog.
Wenn das Gateway die Events im Netzwerk preis gibt, sollte sich die Unterstützung für diesen Schalter in den Adapter einbauen lassen.

**Comment by kubakuhn** [comment]
Hi, danke für die Antwort.
Habe ich gerade gemacht, doch leider erscheint bei jeden Event was ich triggere nur wieder eine Warnung.
**(397) Could not add new sensor: Type "remote.b286acn02" is not valid, use one of Hub::sensorTypes**

Sonst gibt es keine weiteren Meldungen im Log die den Schalter betreffen.
Ich geh mal davon aus das ist eher schlecht?

**Comment by Diginix** [comment]
Und du hattest auch den Loglevel auf Debug gestellt?
Da kommt normalerweise richtig viel vom Gateway.
Ohne das Log selbst hier zu zeigen, ist es schwer bzw. wenn du das Log selbst in der Form auswertest, gibt es nichts was hier jemand tun kann.

**Comment by kubakuhn** [comment]
Ja hab auch LogLevel Debug gestellt.
Versuche ja zu helfen daher auch gerne das Log.

![mihome 0 log](https://user-images.githubusercontent.com/75815644/101959721-2f8a5f80-3c06-11eb-9db9-ba2739c80d25.PNG)

Die warnings kommen immer zu dem zeitpunkt wenn ich eine Aktion vom Schlater triggere, leider nichts weiter.

Kann auch gerne das Debug Log weiter laufen lassen und noch mehr posten wenn das nicht reicht.
Wäre über Hilfe sehr dankbar.

**Comment by Diginix** [comment]
Hm, ok das Log gibt wirklich nicht mehr her. Da hab ich grad auch keine Idee weiter. Aber bestimmt einer der Entwickler.

**Comment by kubakuhn** [comment]
Hey, hab deine Nachricht jetzt erst gelesen.
Frohes Neues Jahr erstmal.
Also wenn das Angebot noch steht und du meinst dass du das hinkriegst würd ich dir son Ding mal vorbei schicken. Daran sollte es nicht scheitern.

LG

**Comment by Diginix** [comment]
@kubakuhn Danke für das Angebot. Da es gut sein kann, dass nur das Hinzufügen des Typs in die devices.js nicht reicht und ich dann womöglich auch am Ende mit meinen Fähigkeiten bin, wäre der Versand an eine fitteren Entwickler wie @GermanBluefox sinnvoller. Allerdings weiß ich nicht ob er noch immer Xiaomi Hardware hat und speziell das Gateway um diesen Schalter bei sich auch koppeln zu können.
Vllt liest er diesen Kommentar hier und kann helfen.

**Comment by kubakuhn** [comment]
Hab gerade mal selbst probiert das zu machen wie du beschrieben hast.
Vielen lieben dank für die "Kurzanleitung" hab mir noch nie Adaptercode angeschaut vorher.
Und ich bin beeindruckt, aber es klappt wirklich :)

Juhu endlich kann ich die Schalter benutzen :D

**Comment by Diginix** [comment]
Cool, dass es so einfach ging. Funktionieren denn alle Tasten und auch Events (Einfach, Lang, Doppel ...)?
Kannst mir ja die devices.js hier anhängen und ich schau auch noch mal drüber und kann dann ggf. ein Pullrequest erstellen, damit es irgendwann in die offizielle Version mit übernommen wird. Ansonsten müsstest du vorerst auf Updates verzichten, weil sonst der Code wieder überschrieben würde. Bzw. musst du die Datei nach jedem Update neu mit diesen Teil ergänzen.

**Comment by kubakuhn** [comment]
Klar gerne hab nur folgenden Code hinzugefügt:


    remote_b286acn02: {type: 'remote.b286acn02',   fullName: 'Xiaomi Aqara Wireless Remote Switch (Double Rocker)', ClassName: WallButtons, states: {
            voltage:          states.voltage,
            percent:          states.percent,

            channel_0:        states.channel_0,
            channel_0_double: states.channel_0_double,
            channel_0_long:   states.channel_0_long,
            channel_1:        states.channel_1,
            channel_1_double: states.channel_1_double,
            channel_1_long:   states.channel_1_long,
            dual_channel:     states.dual_channel,
        }
    },

Man kann keine js Dateien hochladen, hab es desshalb mal in txt umbenannt.

[devices.txt](https://github.com/ioBroker/ioBroker.mihome/files/5769329/devices.txt)

**Comment by GermanBluefox** [comment]
> @kubakuhn Danke für das Angebot. Da es gut sein kann, dass nur das Hinzufügen des Types in die devices.js nicht reicht und ich dann womöglich auch am Ende mit meinen Fähigkeiten bin, wäre der Versand an einen fitteren Entwickler wie @GermanBluefox sinnvoller. Allerdings weiß ich nicht ob er noch immer Xiaomi Hardware hat und speziell das Gateway, um deinen Schalter bei sich auch koppeln zu können.
> Vllt. liest er diesen Kommentar hier und kann helfen.

Ich habe Hardware nicht mehr, aber was noch schlimmer ist, ich habe keine Zeit...

**Comment by GermanBluefox** [comment]
> Klar gerne hab nur folgenden Code hinzugefügt:
> 
> 
>     remote_b286acn02: {type: 'remote.b286acn02',   fullName: 'Xiaomi Aqara Wireless Remote Switch (Double Rocker)', ClassName: WallButtons, states: {
>             voltage:          states.voltage,
>             percent:          states.percent,
> 
>             channel_0:        states.channel_0,
>             channel_0_double: states.channel_0_double,
>             channel_0_long:   states.channel_0_long,
>             channel_1:        states.channel_1,
>             channel_1_double: states.channel_1_double,
>             channel_1_long:   states.channel_1_long,
>             dual_channel:     states.dual_channel,
>         }
>     },
> 
> Man kann keine js Dateien hochladen, hab es desshalb mal in txt umbenannt.
> 
> [devices.txt](https://github.com/ioBroker/ioBroker.mihome/files/5769329/devices.txt)
> 

Es wäre hilfreich, das in Form eines PR zu haben

**Comment by Diginix** [comment]
Wenn ich dazu komme übernehme ich die Erweiterung von kubakuhn in mein Fork und erstelle ein PR.
