### ISSUE TITLE
Add bedside lamp 3 

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.mihome#135]
I'm using a xiaomi bedside lamp 3 and it's working via xiaomi app. I would appreciate if it could be added to the mihome adapter too.

**Comment by Diginix** [comment]
Is it wifi or zigbee?
My bedside lamp 2 is direct connected via wifi with my ap and works with the yeelight adapter.
Mihome adapter supports only zigbee (sub)devices that are connected directly with the Xiaomi gateway. Not all what is useable with the MiHome app, can be integrated in this adapter.
If the bedside lamp 3 is zigbee, you should provide a log with level debug where communication from the bedside lamp is shown.

**Comment by passuff** [comment]
You're right, it's wifi and additionally not version 3 but 2. I just downloaded the yeelight adapter but it seems just bslamp1 is supported. I will try to find more information. Thx a lot.

**Comment by Diginix** [comment]
My Xiaomi Mijia bedside lamp 2 works with Yeelight adapter 1.0.3
![image](https://user-images.githubusercontent.com/39678667/103089202-87a16880-45ed-11eb-838f-ce1edcd8c536.png)

It is this model:
![image](https://user-images.githubusercontent.com/39678667/103089270-cf27f480-45ed-11eb-976d-927833f83d97.png)

But enough offtopic. ;-)
You can create an issue on Yeelight adapter with more specific details like model number and the debug log.

**Comment by passuff** [comment]
Agree, moved to yeelight. I would appreciate if you could assist me with adding my lamp as it seems there is not much activity:

[https://github.com/iobroker-community-adapters/ioBroker.yeelight-2/issues/73](url)
