### ISSUE TITLE
Xiaomi Magic Cube not be integrated

### ISSUE THREAD

**Issue by nowev** [ioBroker/ioBroker.mihome#14]
I have a Xiaomi Magic Cube, it can not be integrated in ioBroker. In the MiHome this one works. There is another user with this problem in the ioBroker forum. Are there different Magic Cubes?
How can I contribute to problem solving?

**Comment by nowev** [comment]
I'm getting the following message:

mihome.0 | 2018-05-21 21:42:24.112 | warn | Could not add new sensor: Type "sensor_cube.aqgl01" is not valid, use one of  Hub::sensorTypes
-- | -- | -- | --

if I delete the folder 'devices' under Objects and restart the instance.

**Comment by nowev** [comment]
Ist hier nichts machbar?

**Comment by Apollon77** [comment]
Jetzt mach doch mal langsam ... sobald ein Entwickler der hier Ahnung hat Zeit hast schaut er sich das an.
Wenn es der offizielle Nachfolger ist bin ich sicher das da was geht.

**Comment by GermanBluefox** [comment]
Done on github
