### ISSUE TITLE
Air Purifier 3H mit iobroker / iOS ?

### ISSUE THREAD

**Issue by v8turbo** [ioBroker/ioBroker.mihome#141]
huhu, ich habe die readme (iOS - You first need to enable local network functions by using the iOS Mi Home App iosApp Mi Install the App on a iOS device..........) versucht zu befolgen. Leider happert es schon bei Schritt 3... Welches Gateway in Mi Home soll ich auswählen ?!? Es gibt gar keins. Auch finde ich unter About kein Dev Mode.... ??

Gibt es evtl. eine neue Version von der iOS App die das nicht mehr hat ?

**Comment by SlippySken** [comment]
Mh, nee, hab das gleiche Problem mit der Android App
