### ISSUE TITLE
has to be type "number" but received type "boolean

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.mihome#148]
JS-Controller 3.3.15

Meldung `mihome.0 State value to set for "mihome.0.devices.plug_158d00020d98af.inuse" has to be type "number" but received type "boolean"` kommt laufend.

**Comment by Apollon77** [comment]
object deleted? still?

**Comment by Negalein** [comment]
Objekte gelöscht
Fehler bleibt

`State value to set for "mihome.0.devices.plug_158d0001f24aad.inuse" has to be type "number" but received type "boolean"`

**Comment by VLGorskij** [comment]
correction suggested in Pull request  https://github.com/ioBroker/ioBroker.mihome/pull/150

**Comment by Negalein** [comment]
> correction suggested in Pull request #150

gibt es eine neue Version vom Adapter?

**Comment by VLGorskij** [comment]
until the pullrequest is accepted, you can correct the files in the adapter manually

**Comment by GermanBluefox** [comment]
Please test 1.3.8

**Comment by Negalein** [comment]
> Please test 1.3.8

Danke, funktioniert derzeit :)

**Comment by VLGorskij** [comment]
I already use it, so far there are no complaints13.09.2021, 22:11, "Bluefox" ***@***.***>:
Please test 1.3.8
