### ISSUE TITLE
Communication problem if Mihome GW from another network.

### ISSUE THREAD

**Issue by vvfrwl** [ioBroker/ioBroker.mihome#151]
Dear Sirs,
I have communication problems between MiHome adapter and MiHome GW.
It is impossible to connect to MiHome GW from ioBroker from another network.

1. IoBroker adapter can not connect to Mihome GW if IOBroker server and Mihome GW placed to different networks.
IoBroker adapter does not send any traffic to MiHome GW (no attempts to connect to MIGW).
![Connection to MIGW Issue](https://user-images.githubusercontent.com/59322588/134808579-1c45e88a-9e28-4ffa-8258-f8cb1f83a66f.jpg)

It has been checked by tcpdump on ioBroker server during reboot of the MiHome adapter.
It has been checked by tcpdump on the Firewall between ioBroker server and MI GW during reboot of the ioBroker server.

I did not see any communication problems between The IOBroker server and MiHome GW (OS level).
![IOBroker - MIGW Communication](https://user-images.githubusercontent.com/59322588/134808585-1eb2cfd7-d854-4097-8806-515e05c82672.jpg)

! IoBroker adapter works with MiHome GW if ioBroker server and MiHome GW placed to the same network.

UPD.I have found that the ioBroker server uses multicast for establishing connections.  (IOBroker1.9898 > 224.0.0.50.4321: UDP).
It is difficult with L3 routing.
Is it possible to use MiGW IP from the adapter`s setting for L3 connection without multicast (feature request)?

2. Additional:
 IoBroker interface does not apply in adapter settings.
 It is impossible to allow the port for one "internal" interface only.
Adapter opens the port 9898 on all interface only (0.0.0.0:9898) or does not open 9898 port if choosed not "0.0.0.0" interface.
![Interface Issue](https://user-images.githubusercontent.com/59322588/134808592-02dbc9c5-9bda-4f8d-9bfb-b4beb2c4840f.jpg)

Platform       : linux
os             : Armbian Buster with Linux 5.3.0-aml-g12
Architecture   : arm64
CPUs           : 6
Speed          : 100 MHz
Model          : Khadas VIM3 
RAM            : 4 GB
System uptime  : 00:21:51
Node.js        : v12.22.6
Disk size      : 27.8 GiB
Disk free      : 23.0 GiB
adapters count : 360
NPM            : v6.14.15
js-controller  : 3.3.18
MiHome adapter : 1.3.7

**Comment by Apollon77** [comment]
youneed to make sure thet eihghter UDP is routed or the hist is in  the network

**Comment by vvfrwl** [comment]
I guess, it`s about the usage of multicast routing (like PIM: Protocol-Independent Multicast).
Routers have TCP\UDP L3 routing by default.
