### ISSUE TITLE
preferred device gateway with getting token/gateway key

### ISSUE THREAD

**Issue by grogo08** [ioBroker/ioBroker.mihome#153]
Hi, i want to start building a netwaork in IOBroker with my xiaomi cube devices. 

Therefor I bought a mijia xiaomi gateway, but I cannot get token/gateway key, because the "three dots" dont appear in app and i could not switch in development mode to get token. 

I dont found a description to solve the problem. I thought it could not so difficult to get a program for PC-OS to read token, but i found nothing that way.

So i decide to buy a new gateway. Is there a shop how sell gateway with gateway key or is it easear with another gateway device to get key/token?

Thanks a lot for your help to start with my xiaomi network

best regards,

grogo

**Comment by tarkrai** [comment]
sam problem here...
