### ISSUE TITLE
Feature request: Connection state for multiple gateways

### ISSUE THREAD

**Issue by grdminer** [ioBroker/ioBroker.mihome#16]
Dear Team,

the mihome adapter allows multiple gateways per instance but provides only one connection state info.connection. Would it be possible to add states for each gateway or add a heartbeat (each gateway sends a heartbeat) state for each gateway in device tree? I have more than one gateway connected and the state connected stay true even if one gateway is disconnected.

Heartbeats:
* mihome.0	2018-06-01 20:50:17.202	debug	RAW: {"cmd":"heartbeat","model":"gateway","sid":"...b8f","short_id":"0","token":"...","data":{"ip":"x.y.z.16"}}
* mihome.0	2018-06-01 20:50:15.127	debug	RAW: {"cmd":"heartbeat","model":"gateway","sid":"...511","short_id":"0","token":"...","data":{"ip":"x.y.z.17"}}

Many Thanks & Best Regards

**Comment by grdminer** [comment]
Dear Team,

any news for this topic?

Best Regards

**Comment by GermanBluefox** [comment]
No news

вт, 26 июн. 2018 г., 10:06 grdminer <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Done on github

**Comment by grdminer** [comment]
Thanks a lot!
