### ISSUE TITLE
mihome adapter crash since i updated my other adapters

### ISSUE THREAD

**Issue by atifan** [ioBroker/ioBroker.mihome#165]
Two days ago i updated a few adapter in my iobroker (node.js, and some other). Since this update, my mihome adapter does not work correctly and always crashs. In log i see this message. I dont know the exact cause of this issue but i think its because of the node.js adapter update.

![image](https://user-images.githubusercontent.com/58658412/156901087-222f2583-a651-45ca-9f9e-ebb08d23501c.png)

**Comment by Apollon77** [comment]
Then check the configuration ... there seems to be an error in one of the "keys". I will catch that erro rin next update
