### ISSUE TITLE
Feature Request: Sync device names to ioBroker

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.mihome#18]
Currently a user can name each device in the App/Gateway. Inside ioBroker these names never appear but have to be given again.

When adding a number of new devices at once it becomes tricky to know which of the crypitc names/ids inside ioBroker belongs to which actual device.

It would be great if the device names from the Gateway could be synced to ioBroker

**Comment by GermanBluefox** [comment]
Could you provide th debug outputs in ioBroker from Gateway with name information?
It could be so, that the Gateway do not give the names away via API.

**Comment by GermanBluefox** [comment]
Closed, because no answer

**Comment by martinschm** [comment]
Hi,

sorry for the delay. Didn't see the question untitl now. I copied some of the output:

`mihome.0	2019-01-05 12:12:26.709	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d0001fa5cab.pressure {"val":986.4,"ack":true,"ts":1546686746704,"q":0,"from":"system.adapter.mihome.0","lc":1546686746704}
mihome.0	2019-01-05 12:12:26.706	debug	RAW: {"cmd":"report","model":"weather.v1","sid":"158d0001fa5cab","short_id":46142,"data":{"pressure":"98640"}}
mihome.0	2019-01-05 12:12:26.706	debug	data: 158d0001fa5cab(weather.v1): {"pressure":986.4}
mihome.0	2019-01-05 12:12:26.655	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d0001fa5cab.humidity {"val":27.26,"ack":true,"ts":1546686746650,"q":0,"from":"system.adapter.mihome.0","lc":1546686746650}
mihome.0	2019-01-05 12:12:26.652	debug	RAW: {"cmd":"report","model":"weather.v1","sid":"158d0001fa5cab","short_id":46142,"data":{"humidity":"2726"}}
mihome.0	2019-01-05 12:12:26.651	debug	data: 158d0001fa5cab(weather.v1): {"humidity":27.26}
mihome.0	2019-01-05 12:12:26.634	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d0001fa5cab.temperature {"val":31.27,"ack":true,"ts":1546686746629,"q":0,"from":"system.adapter.mihome.0","lc":1546686746629}
mihome.0	2019-01-05 12:12:26.631	debug	RAW: {"cmd":"report","model":"weather.v1","sid":"158d0001fa5cab","short_id":46142,"data":{"temperature":"3127"}}
mihome.0	2019-01-05 12:12:26.630	debug	data: 158d0001fa5cab(weather.v1): {"temperature":31.27}
mihome.0	2019-01-05 12:12:26.340	debug	RAW: {"cmd":"heartbeat","model":"gateway","sid":"111111111","short_id":"0","token":"aaaaaa","data":{"ip":"192.168.xx"}}
mihome.0	2019-01-05 12:12:18.869	debug	RAW: {"cmd":"heartbeat","model":"gateway","sid":"2222222","short_id":"0","token":"bbbbb","data":{"ip":"192.168.xx"}}
mihome.0	2019-01-05 12:12:16.363	debug	RAW: {"cmd":"heartbeat","model":"gateway","sid":"111111111","short_id":"0","token":"cccc","data":{"ip":"192.168.xx"}}
mihome.0	2019-01-05 12:12:09.140	debug	system.adapter.admin.0: logging true`


`mihome.0	2019-01-05 12:12:07.493	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d000223a209.humidity {"val":82.54,"ack":true,"ts":1546686727440,"q":0,"from":"system.adapter.mihome.0","lc":1546684387031}
mihome.0	2019-01-05 12:12:07.493	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d000223a209.temperature {"val":16.28,"ack":true,"ts":1546686727439,"q":0,"from":"system.adapter.mihome.0","lc":1546684387029}
mihome.0	2019-01-05 12:12:07.492	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d000223a209.percent {"val":78.5,"ack":true,"ts":1546686727439,"q":0,"from":"system.adapter.mihome.0","lc":1546511933151}
mihome.0	2019-01-05 12:12:07.492	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d000223a209.voltage {"val":2.985,"ack":true,"ts":1546686727438,"q":0,"from":"system.adapter.mihome.0","lc":1546511933151}
mihome.0	2019-01-05 12:12:07.492	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d0001e54933.pressure {"val":986.3,"ack":true,"ts":1546686727438,"q":0,"from":"system.adapter.mihome.0","lc":1546685624635}
mihome.0	2019-01-05 12:12:07.491	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d0001e54933.humidity {"val":58.45,"ack":true,"ts":1546686727437,"q":0,"from":"system.adapter.mihome.0","lc":1546685624556}
mihome.0	2019-01-05 12:12:07.491	debug	redis pmessage io.mihome.0.devices.* io.mihome.0.devices.weather_v1_158d0001e54933.temperature {"val":17.32,"ack":true,"ts":1546686727437,"q":0,"from":"system.adapter.mihome.0","lc":1546685624547}
mihome.0`
