### ISSUE TITLE
Instances status is constantly changing from green to yellow

### ISSUE THREAD

**Issue by Smarti15** [ioBroker/ioBroker.mihome#20]
Hello, what could it be, this is the adapter status under instance constantly changes from green to yellow. Once he says green and connected to the gateway and then he changes to yellow and says that he is not connected to the gateway. He makes this change every few seconds.

The status remains permanently green when "Connected to Host" and "Life Sign". When "Connected with MiHome" he always changes to red.

**Comment by GermanBluefox** [comment]
Log with debug level?

вс, 24 июн. 2018 г., 18:52 Smarti15 <notifications@github.com>:

**Comment by Smarti15** [comment]
`

mihome.0 | 2018-06-24 19:39:09.795 | debug | RAW: {"cmd":"read_ack","model":"motion","sid":"158d0001a8fa29","short_id":18701,"data":{"voltage":3045}}
-- | -- | -- | --
mihome.0 | 2018-06-24 19:39:09.795 | debug | data: 158d0001a8fa29(motion): {"voltage":3.045,"percent":84.5}
mihome.0 | 2018-06-24 19:39:09.795 | debug | device: 158d0001a8fa29(motion)
mihome.0 | 2018-06-24 19:39:09.795 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201c885","short_id":23274,"data":{"voltage":3035,"temperature":"2752","humidity":"3865"}}
mihome.0 | 2018-06-24 19:39:09.795 | debug | data: 158d000201c885(sensor_ht): {"voltage":3.035,"percent":83.5,"temperature":27.52,"humidity":38.65}
mihome.0 | 2018-06-24 19:39:09.795 | debug | device: 158d000201c885(sensor_ht)
mihome.0 | 2018-06-24 19:39:09.795 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d0001bc542e","short_id":55381,"data":{"voltage":3082}}
mihome.0 | 2018-06-24 19:39:09.795 | debug | data: 158d0001bc542e(switch): {"voltage":3.082,"percent":88.2}
mihome.0 | 2018-06-24 19:39:09.795 | debug | device: 158d0001bc542e(switch)
mihome.0 | 2018-06-24 19:39:09.795 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001d839ab","short_id":46782,"data":{"voltage":3005,"status":"close"}}
mihome.0 | 2018-06-24 19:39:09.795 | debug | data: 158d0001d839ab(magnet): {"voltage":3.005,"percent":80.5,"state":false}
mihome.0 | 2018-06-24 19:39:09.795 | debug | device: 158d0001d839ab(magnet)
mihome.0 | 2018-06-24 19:39:09.795 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201f4d3","short_id":53142,"data":{"voltage":3025,"temperature":"2426","humidity":"4815"}}
mihome.0 | 2018-06-24 19:39:09.795 | debug | data: 158d000201f4d3(sensor_ht): {"voltage":3.025,"percent":82.5,"temperature":24.26,"humidity":48.15}
mihome.0 | 2018-06-24 19:39:09.795 | debug | device: 158d000201f4d3(sensor_ht)
mihome.0 | 2018-06-24 19:39:09.795 | debug | RAW:   {"cmd":"read_ack","model":"gateway","sid":"7811dce1d311","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-06-24 19:39:09.795 | debug | data: 7811dce1d311(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-06-24 19:39:09.782 | debug | RAW:   {"cmd":"get_id_list_ack","sid":"7811dce1d311","token":"xRhmuAeSCwUhr81r","data":["158d000201f4d3","158d0001d839ab","158d0001bc542e","158d000201c885","158d0001a8fa29"]}
mihome.0 | 2018-06-24 19:39:09.380 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dce1d311","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.74"}
mihome.0 | 2018-06-24 19:39:09.379 | debug | device: 7811dce1d311(gateway)
mihome.0 | 2018-06-24 19:38:55.932 | debug | system.adapter.admin.0: logging true
mihome.0 | 2018-06-24 19:38:19.249 | debug | RAW: {"cmd":"read_ack","model":"motion","sid":"158d0001a8fa29","short_id":18701,"data":{"voltage":3045}}
mihome.0 | 2018-06-24 19:38:19.248 | debug | data: 158d0001a8fa29(motion): {"voltage":3.045,"percent":84.5}
mihome.0 | 2018-06-24 19:38:19.248 | debug | device: 158d0001a8fa29(motion)
mihome.0 | 2018-06-24 19:38:19.248 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201c885","short_id":23274,"data":{"voltage":3035,"temperature":"2752","humidity":"3865"}}
mihome.0 | 2018-06-24 19:38:19.248 | debug | data: 158d000201c885(sensor_ht): {"voltage":3.035,"percent":83.5,"temperature":27.52,"humidity":38.65}
mihome.0 | 2018-06-24 19:38:19.248 | debug | device: 158d000201c885(sensor_ht)
mihome.0 | 2018-06-24 19:38:19.248 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d0001bc542e","short_id":55381,"data":{"voltage":3082}}
mihome.0 | 2018-06-24 19:38:19.248 | debug | data: 158d0001bc542e(switch): {"voltage":3.082,"percent":88.2}
mihome.0 | 2018-06-24 19:38:19.248 | debug | device: 158d0001bc542e(switch)
mihome.0 | 2018-06-24 19:38:19.248 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001d839ab","short_id":46782,"data":{"voltage":3005,"status":"close"}}
mihome.0 | 2018-06-24 19:38:19.247 | debug | data: 158d0001d839ab(magnet): {"voltage":3.005,"percent":80.5,"state":false}
mihome.0 | 2018-06-24 19:38:19.247 | debug | device: 158d0001d839ab(magnet)
mihome.0 | 2018-06-24 19:38:19.247 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201f4d3","short_id":53142,"data":{"voltage":3025,"temperature":"2426","humidity":"4815"}}
mihome.0 | 2018-06-24 19:38:19.247 | debug | data: 158d000201f4d3(sensor_ht): {"voltage":3.025,"percent":82.5,"temperature":24.26,"humidity":48.15}
mihome.0 | 2018-06-24 19:38:19.247 | debug | device: 158d000201f4d3(sensor_ht)
mihome.0 | 2018-06-24 19:38:19.246 | debug | RAW:  {"cmd":"read_ack","model":"gateway","sid":"7811dce1d311","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-06-24 19:38:19.246 | debug | data: 7811dce1d311(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-06-24 19:38:19.240 | debug | RAW:  {"cmd":"get_id_list_ack","sid":"7811dce1d311","token":"8JDBqYfiw8S8M45B","data":["158d000201f4d3","158d0001d839ab","158d0001bc542e","158d000201c885","158d0001a8fa29"]}
mihome.0 | 2018-06-24 19:38:19.206 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dce1d311","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.74"}
mihome.0 | 2018-06-24 19:38:19.206 | debug | device: 7811dce1d311(gateway)
mihome.0 | 2018-06-24 19:37:29.131 | debug | RAW: {"cmd":"read_ack","model":"motion","sid":"158d0001a8fa29","short_id":18701,"data":{"voltage":3045}}
mihome.0 | 2018-06-24 19:37:29.131 | debug | data: 158d0001a8fa29(motion): {"voltage":3.045,"percent":84.5}
mihome.0 | 2018-06-24 19:37:29.131 | debug | device: 158d0001a8fa29(motion)
mihome.0 | 2018-06-24 19:37:29.131 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201c885","short_id":23274,"data":{"voltage":3035,"temperature":"2752","humidity":"3865"}}
mihome.0 | 2018-06-24 19:37:29.131 | debug | data: 158d000201c885(sensor_ht): {"voltage":3.035,"percent":83.5,"temperature":27.52,"humidity":38.65}
mihome.0 | 2018-06-24 19:37:29.131 | debug | device: 158d000201c885(sensor_ht)
mihome.0 | 2018-06-24 19:37:29.131 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d0001bc542e","short_id":55381,"data":{"voltage":3082}}
mihome.0 | 2018-06-24 19:37:29.131 | debug | data: 158d0001bc542e(switch): {"voltage":3.082,"percent":88.2}
mihome.0 | 2018-06-24 19:37:29.129 | debug | device: 158d0001bc542e(switch)
mihome.0 | 2018-06-24 19:37:29.127 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001d839ab","short_id":46782,"data":{"voltage":3005,"status":"close"}}
mihome.0 | 2018-06-24 19:37:29.127 | debug | data: 158d0001d839ab(magnet): {"voltage":3.005,"percent":80.5,"state":false}
mihome.0 | 2018-06-24 19:37:29.127 | debug | device: 158d0001d839ab(magnet)
mihome.0 | 2018-06-24 19:37:29.127 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201f4d3","short_id":53142,"data":{"voltage":3025,"temperature":"2426","humidity":"4815"}}
mihome.0 | 2018-06-24 19:37:29.127 | debug | data: 158d000201f4d3(sensor_ht): {"voltage":3.025,"percent":82.5,"temperature":24.26,"humidity":48.15}
mihome.0 | 2018-06-24 19:37:29.127 | debug | device: 158d000201f4d3(sensor_ht)
mihome.0 | 2018-06-24 19:37:29.127 | debug | RAW:  {"cmd":"read_ack","model":"gateway","sid":"7811dce1d311","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-06-24 19:37:29.126 | debug | data: 7811dce1d311(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-06-24 19:37:29.120 | debug | RAW:  {"cmd":"get_id_list_ack","sid":"7811dce1d311","token":"EPLWGZK6LVMMPlID","data":["158d000201f4d3","158d0001d839ab","158d0001bc542e","158d000201c885","158d0001a8fa29"]}
mihome.0 | 2018-06-24 19:37:28.717 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dce1d311","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.74"}
mihome.0 | 2018-06-24 19:37:28.717 | debug | device: 7811dce1d311(gateway)
mihome.0 | 2018-06-24 19:36:38.648 | debug | RAW: {"cmd":"read_ack","model":"motion","sid":"158d0001a8fa29","short_id":18701,"data":{"voltage":3045}}
mihome.0 | 2018-06-24 19:36:38.647 | debug | data: 158d0001a8fa29(motion): {"voltage":3.045,"percent":84.5}
mihome.0 | 2018-06-24 19:36:38.647 | debug | device: 158d0001a8fa29(motion)
mihome.0 | 2018-06-24 19:36:38.647 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201c885","short_id":23274,"data":{"voltage":3035,"temperature":"2752","humidity":"3865"}}
mihome.0 | 2018-06-24 19:36:38.646 | debug | data: 158d000201c885(sensor_ht): {"voltage":3.035,"percent":83.5,"temperature":27.52,"humidity":38.65}
mihome.0 | 2018-06-24 19:36:38.646 | debug | device: 158d000201c885(sensor_ht)
mihome.0 | 2018-06-24 19:36:38.646 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d0001bc542e","short_id":55381,"data":{"voltage":3082}}
mihome.0 | 2018-06-24 19:36:38.646 | debug | data: 158d0001bc542e(switch): {"voltage":3.082,"percent":88.2}
mihome.0 | 2018-06-24 19:36:38.646 | debug | device: 158d0001bc542e(switch)
mihome.0 | 2018-06-24 19:36:38.646 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001d839ab","short_id":46782,"data":{"voltage":3005,"status":"close"}}
mihome.0 | 2018-06-24 19:36:38.646 | debug | data: 158d0001d839ab(magnet): {"voltage":3.005,"percent":80.5,"state":false}
mihome.0 | 2018-06-24 19:36:38.646 | debug | device: 158d0001d839ab(magnet)
mihome.0 | 2018-06-24 19:36:38.646 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201f4d3","short_id":53142,"data":{"voltage":3025,"temperature":"2426","humidity":"4815"}}
mihome.0 | 2018-06-24 19:36:38.646 | debug | data: 158d000201f4d3(sensor_ht): {"voltage":3.025,"percent":82.5,"temperature":24.26,"humidity":48.15}
mihome.0 | 2018-06-24 19:36:38.645 | debug | device: 158d000201f4d3(sensor_ht)
mihome.0 | 2018-06-24 19:36:38.644 | debug | RAW:  {"cmd":"read_ack","model":"gateway","sid":"7811dce1d311","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-06-24 19:36:38.644 | debug | data: 7811dce1d311(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-06-24 19:36:38.639 | debug | RAW:  {"cmd":"get_id_list_ack","sid":"7811dce1d311","token":"LsSV9sXGraxvrOcD","data":["158d000201f4d3","158d0001d839ab","158d0001bc542e","158d000201c885","158d0001a8fa29"]}
mihome.0 | 2018-06-24 19:36:38.232 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dce1d311","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.74"}
mihome.0 | 2018-06-24 19:36:38.232 | debug | device: 7811dce1d311(gateway)
mihome.0 | 2018-06-24 19:35:45.656 | debug | system.adapter.admin.0: logging false
mihome.0 | 2018-06-24 19:35:27.630 | debug | system.adapter.admin.0: logging true
mihome.0 | 2018-06-24 19:35:14.678 | debug | system.adapter.admin.0: logging false
mihome.0 | 2018-06-24 19:34:58.197 | debug | RAW: {"cmd":"read_ack","model":"motion","sid":"158d0001a8fa29","short_id":18701,"data":{"voltage":3045}}
mihome.0 | 2018-06-24 19:34:58.197 | debug | data: 158d0001a8fa29(motion): {"voltage":3.045,"percent":84.5}
mihome.0 | 2018-06-24 19:34:58.197 | debug | device: 158d0001a8fa29(motion)
mihome.0 | 2018-06-24 19:34:58.197 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201c885","short_id":23274,"data":{"voltage":3035,"temperature":"2752","humidity":"3865"}}
mihome.0 | 2018-06-24 19:34:58.197 | debug | data: 158d000201c885(sensor_ht): {"voltage":3.035,"percent":83.5,"temperature":27.52,"humidity":38.65}
mihome.0 | 2018-06-24 19:34:58.197 | debug | device: 158d000201c885(sensor_ht)
mihome.0 | 2018-06-24 19:34:58.197 | debug | RAW: {"cmd":"read_ack","model":"switch","sid":"158d0001bc542e","short_id":55381,"data":{"voltage":3082}}
mihome.0 | 2018-06-24 19:34:58.197 | debug | data: 158d0001bc542e(switch): {"voltage":3.082,"percent":88.2}
mihome.0 | 2018-06-24 19:34:58.197 | debug | device: 158d0001bc542e(switch)
mihome.0 | 2018-06-24 19:34:58.197 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001d839ab","short_id":46782,"data":{"voltage":3005,"status":"close"}}
mihome.0 | 2018-06-24 19:34:58.197 | debug | data: 158d0001d839ab(magnet): {"voltage":3.005,"percent":80.5,"state":false}
mihome.0 | 2018-06-24 19:34:58.197 | debug | device: 158d0001d839ab(magnet)
mihome.0 | 2018-06-24 19:34:58.197 | debug | RAW:  {"cmd":"read_ack","model":"sensor_ht","sid":"158d000201f4d3","short_id":53142,"data":{"voltage":3025,"temperature":"2426","humidity":"4815"}}
mihome.0 | 2018-06-24 19:34:58.196 | debug | data: 158d000201f4d3(sensor_ht): {"voltage":3.025,"percent":82.5,"temperature":24.26,"humidity":48.15}
mihome.0 | 2018-06-24 19:34:58.196 | debug | device: 158d000201f4d3(sensor_ht)
mihome.0 | 2018-06-24 19:34:58.196 | debug | RAW:  {"cmd":"read_ack","model":"gateway","sid":"7811dce1d311","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-06-24 19:34:58.196 | debug | data: 7811dce1d311(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-06-24 19:34:58.189 | debug | RAW:  {"cmd":"get_id_list_ack","sid":"7811dce1d311","token":"sHSDghN92sUhJJ4b","data":["158d000201f4d3","158d0001d839ab","158d0001bc542e","158d000201c885","158d0001a8fa29"]}
mihome.0 | 2018-06-24 19:34:58.185 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dce1d311","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.74"}
mihome.0 | 2018-06-24 19:34:58.185 | debug | device: 7811dce1d311(gateway)

`

**Comment by mistermaster2punkt0** [comment]
Habe leider genau das selbe Problem. Mein Mihome Adapter will seit mehreren Tagen auch nicht mehr.
Ich hoffe, dass der Fehler identifiziert werden kann. Falls noch irgendwelche Infos fehlen, bitte Bescheid geben!

**Comment by GermanBluefox** [comment]
Leider mit "will seit mehreren Tagen auch nicht mehr" kann ich nicht viel
anfangen.

пн, 25 июн. 2018 г., 11:39 mistermaster2punkt0 <notifications@github.com>:

**Comment by Smarti15** [comment]
Also bei mir lief es noch nie stabil. Probiere mich aber erst seint 2 Wochen an ioBroker. Immer wenn ich es installiere und einrichte, verbindet der Adapter und dann wechselt der Status : Verbunden mit mihome" auf falsch und mal wieder wahr. Ich weiß nicht was ich falsch machen. Hab gestern den ioBroker nochmal komplett neu aufgesetzt, aber wieder das gleiche Problem. Das Gateway selber läuft aber sauber, dort werden die Meldungen immer sofort gemeldet. Das Debug Log hab ich weiter oben mal gepostet, aber ich glaub da sieht man keine Fehler oder?

**Comment by mistermaster2punkt0** [comment]
Es tut mir leid wenn ich die „ Programmierfachsprache“ nicht perfekt beherrsche. Ich bin auch noch totaler Anfänger.
Bei mir hat der Adapter seit längerer Zeit super funktioniert! Dickes Lob an dieser Stelle an den Programmierer!!

Nur leider wechselt er momentan (wie Smarti15 oben beschrieben hat) immer wieder auf gelb (dann steht verbunden mit MiHome auf falsch).
Ich habe 2 Gateways am Laufen.

Was mir aufgefallen ist: Der Gelb Zustand hält immer exakt 30sek an, bis er dann wieder auf grün springt. Im iobroker Forum habe ich das hier gefunden: https://forum.iobroker.net/viewtopic.php?t=6780&start=100
Es scheint wohl ein ähnliches oder das gleiche Probelm gewesen zu sein.

**Comment by GermanBluefox** [comment]
>Hilft dir das weiter oder hab ich da die falschen Logdaten hochgeladen?

Du hast aber kein Wechsel von grün auf gelb mit geschnitten. Oder?

Mihome gateway sollte mindestens einmal in 20 Sekunden ein Packet senden, sonst wird er als disconnected gemeldet.

**Comment by Smarti15** [comment]
So also ich hab den Fehler nicht mehr, seit ich mein Asus Tinker Board habe. Vorher hatte ich einen virtuellen Rasp in der VirtualBox. Da scheint es mit dem Adpater Probleme zu geben. Jetzt läuft alles stabil und bleibt dauerhaft auf grün. Vielen Dank für diesen tollen Adapter :)
