### ISSUE TITLE
heartbeat timeout generates many log entries

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.mihome#21]
The new heartbeat timeout leads to this log entries the whole day:
Is this ok and as expected?
> 
mihome.0 | 2018-06-27 07:29:24.450 | info | Change connection status on timeout after 20000ms: false
mihome.0 | 2018-06-27 07:28:04.270 | info | Change connection status: true
mihome.0 | 2018-06-27 07:27:34.256 | info | Change connection status on timeout after 20000ms: false
mihome.0 | 2018-06-27 07:18:05.864 | info | Change connection status: true
mihome.0 | 2018-06-27 07:17:35.650 | info | Change connection status on timeout after 20000ms: false

**Comment by GermanBluefox** [comment]
Your device sends something only every 10 minutes!
Set the heartbeat timeout to 720000 (12 minutes)


ср, 27 июн. 2018 г. в 10:46, Diginix <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Done...
