### ISSUE TITLE
device request: Mi Remote IR Blaster

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.mihome#22]
Hi there,
is there the possibility to add the support for Xiaomi Mi Remote device?
https://www.china-gadgets.de/xiaomi-wifi-ir-fernbedienung/
https://de.gearbest.com/smart-home/pp_229556.html

I ordered one from China and can already use it with the Xiaomi Home App for controlling my TV, AVR and AIR Conditioner.

The device is really cheap and you can use it for all kind of IR devices.

Thank you in advice.
Matthias

**Comment by Apollon77** [comment]
Please enable debug loglevel for adapter, use te device and attach the log to this issue.

Debug: Instances -> expertmode -> column Loglevel

**Comment by xmace** [comment]
`

mihome.0 | 28.06.2018 15:19 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"aXkSic53qR0nVr4b","data":{"ip":"10.0.0.38"}}
-- | -- | -- | --
mihome.0 | 28.06.2018 15:19 | debug | RAW:   {"cmd":"report","model":"sensor_ht","sid":"158d000221a656","short_id":37549,"data":{"humidity":"5177"}}
mihome.0 | 28.06.2018 15:19 | debug | data:   158d000221a656(sensor_ht): {"humidity":51.77}
mihome.0 | 28.06.2018 15:19 | debug | RAW:   {"cmd":"report","model":"sensor_ht","sid":"158d000221a656","short_id":37549,"data":{"temperature":"2287"}}
mihome.0 | 28.06.2018 15:19 | debug | data:   158d000221a656(sensor_ht): {"temperature":22.87}
mihome.0 | 28.06.2018 15:19 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"SuPZy2ZWnnqIpmKw","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:19 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"VyABjYCNy6Tq0lSp","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:18 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"CA5EdSVGyW6KG6n8","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:18 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"AbvC1iCD3HZXIeCg","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:18 | debug | system.adapter.admin-2.0:   logging false
mihome.0 | 28.06.2018 15:18 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"wAqFrTtsw3PEug3f","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:18 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"o9MYqkS9smsfulFw","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:18 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"7UCrkeysrgoeyUpT","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:18 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"WpIjNuS0BzRD8rVe","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dc64ec08","short_id":"0","token":"1Vb0SxMdFzkIVM5Y","data":{"ip":"10.0.0.38"}}
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_cube.aqgl01","sid":"158d0002564d21","short_id":62500,"data":{"voltage":2975}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d0002564d21(cube): {"voltage":2.975,"percent":77.5}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d0002564d21(cube)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d000221a61e","short_id":11097,"data":{"voltage":3035,"temperature":"10000","humidity":"0"}}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d000221a61e(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"switch","sid":"158d00016bf5df","short_id":58875,"data":{"voltage":3072}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d00016bf5df(switch): {"voltage":3.072,"percent":87.2}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d00016bf5df(switch)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"switch","sid":"158d00016bf5e2","short_id":52482,"data":{"voltage":3062}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d00016bf5e2(switch): {"voltage":3.062,"percent":86.2}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d00016bf5e2(switch)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d000221a553","short_id":60614,"data":{"voltage":3005,"temperature":"2507","humidity":"4675"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d000221a553(sensor_ht):   {"voltage":3.005,"percent":80.5,"temperature":25.07,"humidity":46.75}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d000221a553(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d000221a656","short_id":37549,"data":{"voltage":2985,"temperature":"2339","humidity":"4983"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d000221a656(sensor_ht):   {"voltage":2.985,"percent":78.5,"temperature":23.39,"humidity":49.83}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d000221a656(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_wleak.aq1","sid":"158d000214f494","short_id":30236,"data":{"voltage":3045}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d000214f494(sensor_wleak.aq1):   {"voltage":3.045,"percent":84.5}
mihome.0 | 28.06.2018 15:17 | debug | device:   158d000214f494(sensor_wleak.aq1)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_wleak.aq1","sid":"158d00021509a2","short_id":53371,"data":{"voltage":3025}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d00021509a2(sensor_wleak.aq1):   {"voltage":3.025,"percent":82.5}
mihome.0 | 28.06.2018 15:17 | debug | device:   158d00021509a2(sensor_wleak.aq1)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_wleak.aq1","sid":"158d000211a4a6","short_id":63028,"data":{"voltage":3055}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d000211a4a6(sensor_wleak.aq1):   {"voltage":3.055,"percent":85.5}
mihome.0 | 28.06.2018 15:17 | debug | device:   158d000211a4a6(sensor_wleak.aq1)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_wleak.aq1","sid":"158d000214f470","short_id":51154,"data":{"voltage":3045}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d000214f470(sensor_wleak.aq1):   {"voltage":3.045,"percent":84.5}
mihome.0 | 28.06.2018 15:17 | debug | device:   158d000214f470(sensor_wleak.aq1)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d0001fd5d7e","short_id":60344,"data":{"voltage":3035,"temperature":"2428","humidity":"5169"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d0001fd5d7e(sensor_ht):   {"voltage":3.035,"percent":83.5,"temperature":24.28,"humidity":51.69}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d0001fd5d7e(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d000221a6a9","short_id":22795,"data":{"voltage":3005,"temperature":"2411","humidity":"4963"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d000221a6a9(sensor_ht):   {"voltage":3.005,"percent":80.5,"temperature":24.11,"humidity":49.63}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d000221a6a9(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d00017006e0","short_id":21525,"data":{"voltage":3005,"temperature":"2459","humidity":"4990"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d00017006e0(sensor_ht):   {"voltage":3.005,"percent":80.5,"temperature":24.59,"humidity":49.9}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d00017006e0(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"sensor_ht","sid":"158d0001c2c394","short_id":45162,"data":{"voltage":2995,"temperature":"2487","humidity":"4587"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d0001c2c394(sensor_ht):   {"voltage":2.995,"percent":79.5,"temperature":24.87,"humidity":45.87}
mihome.0 | 28.06.2018 15:17 | debug | device: 158d0001c2c394(sensor_ht)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"weather.v1","sid":"158d0001fa844b","short_id":43241,"data":{"voltage":2975,"temperature":"2369","humidity":"4918","pressure":"98610"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   158d0001fa844b(weather.v1):   {"voltage":2.975,"percent":77.5,"temperature":23.69,"humidity":49.18,"pressure":986.1}
mihome.0 | 28.06.2018 15:17 | debug | device:   158d0001fa844b(weather.v1)
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"read_ack","model":"gateway","sid":"7811dc64ec08","short_id":0,"data":{"rgb":0,"illumination":704,"proto_version":"1.1.2"}}
mihome.0 | 28.06.2018 15:17 | debug | data:   7811dc64ec08(gateway):   {"illumination":704,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"get_id_list_ack","sid":"7811dc64ec08","token":"vY617GievPi4gWcQ","data":["158d0001fa844b","158d0001c2c394","158d00017006e0","158d000221a6a9","158d0001fd5d7e","158d000214f470","158d000211
mihome.0 | 28.06.2018 15:17 | debug | RAW:   {"cmd":"iam","port":"9898","sid":"7811dc64ec08","model":"gateway","proto_version":"1.1.2","ip":"10.0.0.38"}
mihome.0 | 28.06.2018 15:17 | info | Change connection status: true
mihome.0 | 28.06.2018 15:17 | debug | device: 7811dc64ec08(gateway)

`

**Comment by Diginix** [comment]
The IR remote is a stand alone device, like the wifi smart sockets (not zigbee).
It is not added as subdevice in the gateway. So, I guess it needs an separate adapter. But there is a workaround for it with miio module:
https://forum.iobroker.net/viewtopic.php?f=33&t=10763

**Comment by GermanBluefox** [comment]
Closed, because only zigbee devices discussed here.
