### ISSUE TITLE
Devices aren't recognized

### ISSUE THREAD

**Issue by DanielRuppen** [ioBroker/ioBroker.mihome#23]
Hi

I installed 1.0.7 on my ioBroker (ioBroker is up2date), installed teh Gateway using my Android phone, added 2 child devices (Temp and Body Sensor) and both sensors work well, show data in the phone app.

Then I installed the adapter, entered the key under general and also under my gateway's IP address

Adapter seem to work but when I check objects I only see teh gateway but no devices

Attached a screenshot from iobroker and an adapter log which shows that the 2 sensors send data to iobroker

Any idea why I can't see the devices?

Thanks in advance
Daniel
[iobroker.log](https://github.com/ioBroker/ioBroker.mihome/files/2192327/iobroker.log)
![2018-07-13_12-47-37](https://user-images.githubusercontent.com/35002007/42688015-fbb8947e-869a-11e8-8248-20f192cc51d1.png)

**Comment by Apollon77** [comment]
Where is the debug log as requested in forum?

**Comment by Apollon77** [comment]
In the log from forum I see a motion sensor and a weather sensor in debug?! Correct?

**Comment by DanielRuppen** [comment]
It's a motion sensor and a Temp/Humidity Sensor.

**Comment by Apollon77** [comment]
So the debug at least show them, so should help to support that soon

**Comment by DanielRuppen** [comment]
After removing all adapters, rebotting the system teh problen wasn't resolved, I installed iobroker from scratch and now it works.
