### ISSUE TITLE
Could not add new switch ctrl_ln1 - Xiaomi Aqara 86 Fire Wall Switch One Button

### ISSUE THREAD

**Issue by braverynew** [ioBroker/ioBroker.mihome#24]
Hi bluefox!
I have Aqara switch one button 86, but I can not add to device. Here is my log

mihome.0 | 2018-07-18 05:47:24.110 | warn | Could not add new sensor: Type "ctrl_ln1.aq1" is not valid, use one of Hub::sensorTypes
-- | -- | -- | --
mihome.0 | 2018-07-18 05:47:24.075 | warn | Could not add new sensor: Type "ctrl_ln1.aq1" is not valid, use one of Hub::sensorTypes

Pls help me to add this switch to device

**Comment by GermanBluefox** [comment]
Done on github
