### ISSUE TITLE
The heartbeat (Door Sensor, PIR, etc.).

### ISSUE THREAD

**Issue by Sergio-tix** [ioBroker/ioBroker.mihome#28]
Most recently, my Door Sensor and Motion Sensor sent heartbeat.  Door Sensor every 51 minutes sent his fortune true or false. So I realized that the sensor is online and working. I even developed an alert if Door Sensor not responding: https://forum.iobroker.net/viewtopic.php?p=152942#p152942
But now the heartbeat stopped coming. Now I can not distinguish, there are no events, or Door Sensor not work.
I could not understand why it stopped heartbeat. I simultaneously updated Xiaomi MiHome Gateway and updated mihome xiaomi driver iobroker from version 1.0.5 to version 1.0.7.
Earlier the heartbeat Door Sensor was determined only in iobroker (Node-RED), in log xiaomi mihome did not have heartbeat. Consequently, the system Xiaomi able to distinguish The heartbeat from status signals, Good, if iobroker also will be able to distinguish heartbeat from status.
how do i get back heartbeat Door Sensor?

**Comment by GermanBluefox** [comment]
It seems, that you use node-red for that. Am I right?

**Comment by Sergio-tix** [comment]
Yes i use Node-Red. But it does not matter, because the node just filtered heartbeat

**Comment by Sergio-tix** [comment]
I was wrong. The heartbeat work. But not like before. Heartbeat  - is a battery signal, although it was previously a status sensors.
