### ISSUE TITLE
Device request

### ISSUE THREAD

**Issue by KL-AU-S** [ioBroker/ioBroker.mihome#29]
Is it possible to and the Aqara Smart Motion Sensor device. 
Link:
https://de.gearbest.com/smart-home-controls/pp_009661787808.html
Logfile:

mihome.0 | 2018-08-31 17:30:59.129 | debug | RAW:  {"cmd":"heartbeat","model":"gateway","sid":"7811dcdeaf46","short_id":"0","token":"8tdJBYnfQdNYNAud","data":{"ip":"192.168.0.185"}}
-- | -- | -- | --
mihome.0 | 2018-08-31 17:30:57.253 | warn | Could not add new sensor: Type "vibration" is not valid, use one of  Hub::sensorTypes
mihome.0 | 2018-08-31 17:30:57.253 | debug | RAW: {"cmd":"read_ack","model":"sensor_switch.aq2","sid":"158d0002130b06","short_id":13795,"data":{"voltage":3105}}
mihome.0 | 2018-08-31 17:30:57.253 | debug | data: 158d0002130b06(switch): {"voltage":3.105,"percent":90.5}
mihome.0 | 2018-08-31 17:30:57.253 | debug | device: 158d0002130b06(switch)
mihome.0 | 2018-08-31 17:30:57.253 | debug | RAW: {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d000236a7f2","short_id":7070,"data":{"voltage":3035,"lux":"35"}}
mihome.0 | 2018-08-31 17:30:57.253 | debug | data: 158d000236a7f2(sensor_motion.aq2): {"voltage":3.035,"percent":83.5,"lux":35}
mihome.0 | 2018-08-31 17:30:57.253 | debug | device: 158d000236a7f2(sensor_motion.aq2)
mihome.0 | 2018-08-31 17:30:57.253 | debug | RAW:  {"cmd":"read_ack","model":"gateway","sid":"7811dcdeaf46","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-08-31 17:30:57.237 | debug | data: 7811dcdeaf46(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-08-31 17:30:57.237 | debug | RAW:  {"cmd":"get_id_list_ack","sid":"7811dcdeaf46","token":"q1TklyCcjTSzuPe8","data":["158d000236a7f2","158d0002130b06","158d0002a925ef"]}
mihome.0 | 2018-08-31 17:30:57.237 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dcdeaf46","model":"gateway","proto_version":"1.1.2","ip":"192.168.0.185"}
mihome.0 | 2018-08-31 17:30:57.237 | info | Change connection status: true
mihome.0 | 2018-08-31 17:30:57.237 | debug | device: 7811dcdeaf46(gateway)
mihome.0 | 2018-08-31 17:30:57.191 | info | Change connection status: false
mihome.0 | 2018-08-31 17:30:57.175 | info | starting. Version 1.0.7 in C:/ioBroker/node_modules/iobroker.mihome, node: v10.5.0
mihome.0 | 2018-08-31 17:30:57.034 | debug | statesDB connected
mihome.0 | 2018-08-31 17:30:57.019 | debug | objectDB connected
host.RITS-PC | 2018-08-31 17:30:56.597 | info | instance system.adapter.mihome.0 started with pid 13872

Kind regards

**Comment by GermanBluefox** [comment]
Done on github

**Comment by KL-AU-S** [comment]
Hi, thanks for adding the device. There might be an error because the device will not be showed on the object page. Logfile:

mihome.0 | 2018-09-14 12:45:53.271 | debug | RAW: {"cmd":"report","model":"gateway","sid":"7811dcdeaf46","short_id":0,"data":{"rgb":0,"illumination":1292}}
-- | -- | -- | --
mihome.0 | 2018-09-14 12:45:53.271 | debug | data: 7811dcdeaf46(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-09-14 12:45:52.224 | debug | RAW:   {"cmd":"heartbeat","model":"gateway","sid":"7811dcdeaf46","short_id":"0","token":"RokUhvCBYhiQ18ad","data":{"ip":"192.168.0.185"}}
mihome.0 | 2018-09-14 12:45:47.239 | debug | system.adapter.admin.0: logging true
mihome.0 | 2018-09-14 12:45:45.566 | debug | RAW:  {"cmd":"read_ack","model":"sensor_magnet.aq2","sid":"158d000248cb6f","short_id":63883,"data":{"voltage":3085,"status":"close"}}
mihome.0 | 2018-09-14 12:45:45.566 | debug | data: 158d000248cb6f(magnet): {"voltage":3.085,"percent":88.5,"state":false}
mihome.0 | 2018-09-14 12:45:45.566 | debug | device: 158d000248cb6f(magnet)
mihome.0 | 2018-09-14 12:45:45.566 | debug | RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00024245c4","short_id":63124,"data":{"voltage":3065,"status":"close"}}
mihome.0 | 2018-09-14 12:45:45.566 | debug | data: 158d00024245c4(magnet): {"voltage":3.065,"percent":86.5,"state":false}
mihome.0 | 2018-09-14 12:45:45.566 | debug | device: 158d00024245c4(magnet)
mihome.0 | 2018-09-14 12:45:45.566 | debug | RAW: {"cmd":"read_ack","model":"vibration","sid":"158d0002a925ef","short_id":10701,"data":{"voltage":3035}}
mihome.0 | 2018-09-14 12:45:45.566 | debug | data: 158d0002a925ef(vibration): {"voltage":3.035,"percent":83.5}
mihome.0 | 2018-09-14 12:45:45.566 | debug | device: 158d0002a925ef(vibration)
mihome.0 | 2018-09-14 12:45:45.566 | debug | RAW: {"cmd":"read_ack","model":"sensor_switch.aq2","sid":"158d0002130b06","short_id":13795,"data":{"voltage":3055}}
mihome.0 | 2018-09-14 12:45:45.566 | debug | data: 158d0002130b06(switch): {"voltage":3.055,"percent":85.5}
mihome.0 | 2018-09-14 12:45:45.566 | debug | device: 158d0002130b06(switch)
mihome.0 | 2018-09-14 12:45:45.566 | debug | RAW: {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d000236a7f2","short_id":7070,"data":{"voltage":3025,"lux":"116"}}
mihome.0 | 2018-09-14 12:45:45.566 | debug | data: 158d000236a7f2(sensor_motion.aq2): {"voltage":3.025,"percent":82.5,"lux":116}
mihome.0 | 2018-09-14 12:45:45.550 | debug | device: 158d000236a7f2(sensor_motion.aq2)
mihome.0 | 2018-09-14 12:45:45.550 | debug | RAW:  {"cmd":"read_ack","model":"gateway","sid":"7811dcdeaf46","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.1.2"}}
mihome.0 | 2018-09-14 12:45:45.550 | debug | data: 7811dcdeaf46(gateway): {"illumination":1292,"connected":true,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0 | 2018-09-14 12:45:45.535 | debug | RAW:  {"cmd":"get_id_list_ack","sid":"7811dcdeaf46","token":"yy9wp90vLs2sLgHR","data":["158d000236a7f2","158d0002130b06","158d0002a925ef","158d00024245c4","158d000248cb6f"]}
mihome.0 | 2018-09-14 12:45:45.535 | debug | RAW: {"cmd":"iam","port":"9898","sid":"7811dcdeaf46","model":"gateway","proto_version":"1.1.2","ip":"192.168.0.185"}
mihome.0 | 2018-09-14 12:45:45.535 | info | Change connection status: true
mihome.0 | 2018-09-14 12:45:45.535 | debug | device: 7811dcdeaf46(gateway)
mihome.0 | 2018-09-14 12:45:45.441 | info | Change connection status: false
mihome.0 | 2018-09-14 12:45:45.425 | info | starting. Version 1.1.0 in C:/ioBroker/node_modules/iobroker.mihome, node: v10.5.0
mihome.0 | 2018-09-14 12:45:45.300 | debug | statesDB connected
mihome.0 | 2018-09-14 12:45:45.285 | debug | objectDB connected

Screenshoot Object page:
![grafik](https://user-images.githubusercontent.com/42833559/45546124-a7496400-b81c-11e8-897d-fc32a349243c.png)

**Comment by GermanBluefox** [comment]
Please try one more time with the latest version
