### ISSUE TITLE
Could not add new sensor: Type "sensor_switch.aq3" is not valid

### ISSUE THREAD

**Issue by belko-nsk** [ioBroker/ioBroker.mihome#31]
good afternoon. I bought the button, but it does not appear in the objects.
Log:
Could not add new sensor: Type "sensor_switch.aq3" is not valid, use one of Hub::sensorTypes
Link:
http://www.dx.com/p/Xiaomi-Aqara-Smart-Wireless-Switch-Key-Built-In-Gyro-Function-ZigBee-WiFi-Works-With-Xiaomi-Smart-Home-Mijia-Mi-Home-APP-White-916499969

**Comment by GermanBluefox** [comment]
Please provide the debug log

пн, 10 сент. 2018 г., 15:47 belko-nsk <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Done on github
