### ISSUE TITLE
Не работает настенная розетка Aqara QBCZ11LM

### ISSUE THREAD

**Issue by mafof** [ioBroker/ioBroker.mihome#32]
Пытался добавить его в ручную добавив в файле lib/mihome/Hub.js к переменной sensorTypes следующую строку:
`ctrl_86plug_aq1:'çtrl_86plug.aq1',`
Потом в функции sensorFactory в конструкцию switch добавил переменную
`this.sensorTypes.ctrl_86plug_aq1`
В итоге получилось так:
`
            case this.sensorTypes.plug:
            case this.sensorTypes.plug86:
            case this.sensorTypes.ctrl_86plug_aq1:
                sensor = new Plug(sid, ip, this);
                break;
`
Так же потом в файле main.js к константе `names` прибавил следующее:
`'çtrl_86plug.aq1':   'Xiaomi new Super Plug'`
И в этом же файле добавил к конструкции switch в функции `createDevice` переменную `çtrl_86plug.aq1` к розеткам.
Лог который приходит:
![2018-09-10 13 30 25](https://user-images.githubusercontent.com/16632504/45318930-0ff7be80-b547-11e8-9521-69744b883279.png)
В объектах розетка не появляется

**Comment by GermanBluefox** [comment]
Почему закрыл?

**Comment by mafof** [comment]
Ошибся с наименованием датчика где то в коде, сделал все по новой как писал в вопросе, и все заработало.

**Comment by GermanBluefox** [comment]
I must to take the changes into code.
Or.. @mafof can you create PR?

**Comment by GermanBluefox** [comment]
Done on github
