### ISSUE TITLE
Das wird nicht unterstüzt:

### ISSUE THREAD

**Issue by xXHamtaroXx** [ioBroker/ioBroker.mihome#34]
Es wird nicht der Long klick bei den eckigen wireless switchen unterstüzt...

MfG

Hamtaro

**Comment by Apollon77** [comment]
Bitte Adapter auf debug loglevel schalten und log einer solchen Aktion senden

**Comment by xXHamtaroXx** [comment]
How can i do this?
i cant see the long click in the MiHome App.

Thanks Hamtaro

**Comment by GermanBluefox** [comment]
Just switch mihome adapter to debug level (expert mode)

**Comment by xXHamtaroXx** [comment]
Wie geht das?

Mit freundlichem Gruß

Jamie Albring

Bluefox <notifications@github.com> schrieb am Sa., 15. Sep. 2018, 22:51:

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.docs/blob/master/archive/faq/003_Admin/006-de-how%20to%20enable%20debug%20logs.md

**Comment by xXHamtaroXx** [comment]
der Long Click wird als Single Click erkannt...

Mit freundlichem Gruß

Hamtaro

**Comment by GermanBluefox** [comment]
Es sieht so aus, dass es nicht möglich wird. Da Button kein "click:false" oder "long_click_press" Ereignisse sendet.

**Comment by wowik2018** [comment]
mihome.0 | 2018-11-20 18:44:44.477 | debug | RAW: {"cmd":"report","model":"remote.b286acn01","sid":"158d0002829c5c","short_id":37,"data":{"channel_0":"long_click"}}
-- | -- | -- | --

**Comment by wowik2018** [comment]
Es wird nicht der lange klick bei den eckigen wireless switchen unterstüzt.

**Comment by wowik2018** [comment]
Hallo, können Sie bitte bei diesem Schalter long click im Iobroker realisieren?

![cover-xiaomi-switch](https://user-images.githubusercontent.com/45185459/49307663-25411100-f4d6-11e8-82ee-010e05c91fb1.jpg)

**Comment by Hiffi** [comment]
Würde mich auch interessieren.

**Comment by solarsnoop** [comment]
wäre coll wenn man den Tastendruck auch schreiben könnte, dann könnte man den schalter auch per sprache steuern . Oder das Relais ansich würde unterstützt , das wäre auch cool.

**Comment by GermanBluefox** [comment]
Implemented
