### ISSUE TITLE
Works the upgraded Version of the Xiaomi Gateway?

### ISSUE THREAD

**Issue by xXHamtaroXx** [ioBroker/ioBroker.mihome#35]
Works the upgraded Version of the Xiaomi Gateway?

Thanks Hamtaro

**Comment by Apollon77** [comment]
More details please. Or test it

**Comment by xXHamtaroXx** [comment]
I will test it..but i must wait for the shipping...so i would ask so an
other person had a xiaomi gateway upgraded version, i hope.

Mit freundlichem Gruß

Jamie Albring

Ingo Fischer <notifications@github.com> schrieb am Fr., 14. Sep. 2018,
07:39:

**Comment by Apollon77** [comment]
Such questions are maybe better in the forum

**Comment by xXHamtaroXx** [comment]
Okay

Mit freundlichem Gruß

Jamie Albring

Ingo Fischer <notifications@github.com> schrieb am Fr., 14. Sep. 2018,
07:47:
