### ISSUE TITLE
Arara Cube can not connect with iobroker

### ISSUE THREAD

**Issue by fischi87** [ioBroker/ioBroker.mihome#38]
Hello, i can't add my aqara cube in iobroker. i connected it in my mihome app on my phone but in iobroker:

mihome.0
2018-09-23 13:37:17.593
debug
RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dcb25413","short_id":"0","token":"Dzepen07ewMVfSnl","data":{"ip":"192.168.178.25"}}
mihome.0
2018-09-23 13:37:07.452
debug
RAW: {"cmd":"heartbeat","model":"gateway","sid":"7811dcb25413","short_id":"0","token":"zacKaMKzIxPI2KU2","data":{"ip":"192.168.178.25"}}
mihome.0
2018-09-23 13:36:58.606
warn
Could not add new sensor: Type "sensor_cube.aqgl01" is not valid, use one of Hub::sensorTypes
mihome.0
2018-09-23 13:36:58.601
debug
RAW: {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d000276d3d1","short_id":19034,"data":{"voltage":3055,"lux":"66"}}
mihome.0
2018-09-23 13:36:58.598
debug
data: 158d000276d3d1(sensor_motion.aq2): {"voltage":3.055,"percent":85.5,"lux":66}
mihome.0
2018-09-23 13:36:58.593
debug
device: 158d000276d3d1(sensor_motion.aq2)
mihome.0
2018-09-23 13:36:58.590
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00026a2ad8","short_id":58639,"data":{"voltage":3015,"status":"close"}}
mihome.0
2018-09-23 13:36:58.588
debug
data: 158d00026a2ad8(magnet): {"voltage":3.015,"percent":81.5,"state":false}
mihome.0
2018-09-23 13:36:58.587
debug
device: 158d00026a2ad8(magnet)
mihome.0
2018-09-23 13:36:58.585
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00027b406f","short_id":21644,"data":{"voltage":3045,"status":"close"}}
mihome.0
2018-09-23 13:36:58.583
debug
data: 158d00027b406f(magnet): {"voltage":3.045,"percent":84.5,"state":false}
mihome.0
2018-09-23 13:36:58.582
debug
device: 158d00027b406f(magnet)
mihome.0
2018-09-23 13:36:58.580
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00027b3d4a","short_id":43924,"data":{"voltage":3025,"status":"close"}}
mihome.0
2018-09-23 13:36:58.578
debug
data: 158d00027b3d4a(magnet): {"voltage":3.025,"percent":82.5,"state":false}
mihome.0
2018-09-23 13:36:58.574
debug
device: 158d00027b3d4a(magnet)
mihome.0
2018-09-23 13:36:58.570
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00026a2ba6","short_id":12228,"data":{"voltage":3015,"status":"close"}}
mihome.0
2018-09-23 13:36:58.568
debug
data: 158d00026a2ba6(magnet): {"voltage":3.015,"percent":81.5,"state":false}
mihome.0
2018-09-23 13:36:58.567
debug
device: 158d00026a2ba6(magnet)
mihome.0
2018-09-23 13:36:58.565
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d00026a2b28","short_id":36656,"data":{"voltage":2995,"status":"close"}}
mihome.0
2018-09-23 13:36:58.560
debug
data: 158d00026a2b28(magnet): {"voltage":2.995,"percent":79.5,"state":false}
mihome.0
2018-09-23 13:36:58.559
debug
device: 158d00026a2b28(magnet)
mihome.0
2018-09-23 13:36:58.558
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001f3852d","short_id":47584,"data":{"voltage":3015,"status":"close"}}
mihome.0
2018-09-23 13:36:58.555
debug
data: 158d0001f3852d(magnet): {"voltage":3.015,"percent":81.5,"state":false}
mihome.0
2018-09-23 13:36:58.554
debug
device: 158d0001f3852d(magnet)
mihome.0
2018-09-23 13:36:58.552
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001c2e8d6","short_id":64810,"data":{"voltage":3015,"status":"close"}}
mihome.0
2018-09-23 13:36:58.549
debug
data: 158d0001c2e8d6(magnet): {"voltage":3.015,"percent":81.5,"state":false}
mihome.0
2018-09-23 13:36:58.545
debug
device: 158d0001c2e8d6(magnet)
mihome.0
2018-09-23 13:36:58.543
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001bf6226","short_id":26519,"data":{"voltage":3055,"status":"close"}}
mihome.0
2018-09-23 13:36:58.541
debug
data: 158d0001bf6226(magnet): {"voltage":3.055,"percent":85.5,"state":false}
mihome.0
2018-09-23 13:36:58.538
debug
device: 158d0001bf6226(magnet)
mihome.0
2018-09-23 13:36:58.536
debug
RAW: {"cmd":"read_ack","model":"magnet","sid":"158d0001c2e8b6","short_id":29131,"data":{"voltage":3025,"status":"close"}}
mihome.0
2018-09-23 13:36:58.533
debug
data: 158d0001c2e8b6(magnet): {"voltage":3.025,"percent":82.5,"state":false}
mihome.0
2018-09-23 13:36:58.527
debug
device: 158d0001c2e8b6(magnet)
mihome.0
2018-09-23 13:36:58.524
debug
RAW: {"cmd":"read_ack","model":"gateway","sid":"7811dcb25413","short_id":0,"data":{"rgb":0,"illumination":1292,"proto_version":"1.0.9"}}
mihome.0
2018-09-23 13:36:58.514
debug
data: 7811dcb25413(gateway): {"illumination":1292,"on":false,"dimmer":0,"rgb":"#000000"}
mihome.0
2018-09-23 13:36:58.502
debug
RAW: {"cmd":"get_id_list_ack","sid":"7811dcb25413","token":"3NhnsxACkeBVAi6Q","data":["158d0001c2e8b6","158d0001bf6226","158d0001c2e8d6","158d0001f3852d","158d00026a2b28","158d00026a2ba6","158d00027b
mihome.0
2018-09-23 13:36:58.482
debug
RAW: {"cmd":"iam","port":"9898","sid":"7811dcb25413","model":"gateway","ip":"192.168.178.25"}
mihome.0
2018-09-23 13:36:58.460
debug
device: 7811dcb25413(gateway)
mihome.0
2018-09-23 13:36:58.203
info
starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.mihome, node: v6.14.4
mihome.0
2018-09-23 13:36:58.021
debug
statesDB connected
mihome.0
2018-09-23 13:36:57.772
debug
objectDB connected

whats up with the cube or with the adapter?

greedings

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.mihome#110-2018-09-13

**Comment by GermanBluefox** [comment]
Ist angeschlossen. Bitte ausprobieren.
