### ISSUE TITLE
Wecker aus App hinzufügen

### ISSUE THREAD

**Issue by xXHamtaroXx** [ioBroker/ioBroker.mihome#39]
Hallo,
es wäre cool wenn man mit dem Adapter einen Wecker einstellen kann...mit den Wecktönen der App und wenn man den Wecker dann z.B. über einen Wirelesstaster wieder ausschalten kann.

LG

Hamtaro

**Comment by GermanBluefox** [comment]
Du kannst mit ioBroker alle mögliche Wecker definieren.
Die idee von iobroker - keine andere Apps zu benutzen.

Außerdem, liefert gateway keine Daten dafür.

ср, 3 окт. 2018 г. в 9:47, Hamtaro <notifications@github.com>:
