### ISSUE TITLE
Namen nach Neustart weg

### ISSUE THREAD

**Issue by eumats** [ioBroker/ioBroker.mihome#4]
Hallo,

hat man den Geräten in der Lasche "Objekte" von ioBroker Namen vergeben sind diese nach einem Neustart des Adapter leider wieder weg.
Es wäre toll, wenn die Namen erhalten bleiben würden. Bei mehreren gleichen Geräten erleichtert das die Zuordnung.

MfG
B. Müller

**Comment by GermanBluefox** [comment]
Please test: https://github.com/ioBroker/ioBroker.mihome/commit/e408aab7d42185b03f48757ce56b12611b0dce52

**Comment by GermanBluefox** [comment]
Can you test from github?

**Comment by eumats** [comment]
Perfect. The bug is fixed in V1.0.0. Thank's...

**Comment by misanorot** [comment]
Hey,

at me the bug is still there in v1.0

**Comment by misanorot** [comment]
Hey,

sorry! I reinstall the instance an now it works fine.

**Comment by jangatzke** [comment]
Was fixed without reinstall for me. Thx.
