### ISSUE TITLE
Could not add new sensor: Type "remote.b1acn01" is not valid, use one of Hub::sensorTypes

### ISSUE THREAD

**Issue by de3d0300** [ioBroker/ioBroker.mihome#40]
Hi bluefox!
I have Aqara Smart Wireless Switch (Model:WXKG11LM), but I can not add to device. Here is my log

2018-10-03 18:46:15.038 - warn: mihome.0 Could not add new sensor: Type "remote.b1acn01" is not valid, use one of Hub::sensorTypes
--
2018-10-03 18:46:22.701 - warn: mihome.0 Could not add new sensor: Type "remote.b1acn01" is not valid, use one of Hub::sensorTypes

Can you please support?

Thanks in advance and best wishes

**Comment by GermanBluefox** [comment]
Please do not expect that all NEW devices will be supported automatically or will be added by me in 1 hour. 
Xiaomi creates new devices every week, and it is not so hard to add new types manually if they look like other existing devices. Please show some independence and initiative and create PR.

**Comment by goohnie** [comment]
I am not a programmer. 
I analyzed the code and i could adapt it to the new switch is created.
it works for me.
Unfortunately, I have no idea how I do that on Github.
It would certainly be better, but as I said, I can not really program.
Here are the 3 files that have been modified:

[remote.b186acn01.zip](https://github.com/ioBroker/ioBroker.mihome/files/2457312/remote.b186acn01.zip)

**Comment by GermanBluefox** [comment]
Added in 1.1.2
