### ISSUE TITLE
device icons 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.mihome#42]
Hi,
thank you for this great adapter! I've a small idea for the future, because the icons of the devices are in Iobroker-Admin/Objects and some Adapters like Material, not clear to see - white icons of a white background... my question, it's possible to make a frame or the background of the Icons or the background of the field in admin in another color?? so the contrast is better?

Second thing, the icons of the  "weather" devices are not correct, these are taken from fritz.dect-heating devices.. 
screenshot here:
![image](https://user-images.githubusercontent.com/36229898/46617746-d56d4b80-cb1d-11e8-8f08-cef4b594aa6d.png)

**Comment by GermanBluefox** [comment]
You can find the icons here:
https://github.com/ioBroker/ioBroker.mihome/tree/master/admin/icons

I would appreciate if you will change the icons and provide the PR.

**Comment by Ilovegym66** [comment]
Ahh, ok,. I'm ongoing ..

**Comment by Brainbug01** [comment]
Here is an example, please use it.

![weather_v1_new](https://user-images.githubusercontent.com/35106961/46745545-90781f00-ccad-11e8-88c1-9f93e3d04584.png)

**Comment by GermanBluefox** [comment]
> Here is an example, please use it.

Which type is that?

**Comment by Ilovegym66** [comment]
this is the weather_v1 device.

**Comment by Ilovegym66** [comment]
the current icon for weather_v1 show a china-version of a smart socket:
https://de.gearbest.com/power-strips/pp_341431.html?wid=1433363

**Comment by Brainbug01** [comment]
> Which type is that?

weather_v1

**Comment by Brainbug01** [comment]
Close the issue, 1.2.0 works. Thank you! ( don't forget to delete the cache )
