### ISSUE TITLE
Namen vom Gateway übertragen

### ISSUE THREAD

**Issue by krettek** [ioBroker/ioBroker.mihome#47]
Hallo,

ich hab den Adapter in der letzten Version 1.2.3 laufen.
Leider ist die Anzeige der verschiedenen Sensoren und Schalter in iobroker sehr schwierig, da lediglich die IDs und die generelle Gerätebezeichnung angegeben sind.
In der Beschreibung von 1.1.0 hieß es, dass die Namen übertragen werden.
Waren damit die in der App den Geräten zugewiesenen Namen gemeint? Falls ja, wie krieg ich das hin, dass die übertragen werden. 
Das Löschen der Objekte und das neustarten und neuinstallieren des Adapters hat lediglich dazu geführt, dass die allgemeine Bezeichnung der Geräte von deutsch nach englisch gewechselt hat.

**Comment by Ilovegym66** [comment]
soviel ich weiß, ist das doch nicht möglich, da das Gateway den Namen, der in der App eingetragen ist, nicht mit überträgt. So haben leider alle Devices erstmal den gleichen Namen.. ich habe bei meinen 67 Devices auch einige Mühe gehabt, die alle in iobroker zu benennen, konnte mich aber anhand der Datum/Uhrzeit in den Logs in der App und dem Zeitstempel des Objekts in iobroker behelfen...

**Comment by GermanBluefox** [comment]
Gateway gibt keinen Namen her. Also - ist nicht möglich.
