### ISSUE TITLE
Klimaanlagen Controller

### ISSUE THREAD

**Issue by JvB94** [ioBroker/ioBroker.mihome#48]
Hi,

der Klimaanlagen Controller von Xiaomi wird wohl garnicht unterstützt. Benutze diesen auch als Gateway und schaffe es nicht ihn zu verbinden. Gibt es die möglichkeit das irgendwie hinzubekommen?

**Comment by JvB94** [comment]
mihome.0 | 2018-11-03 03:33:13.192 | warn | Could not add new sensor: Type "acpartner.v3" is not valid, use one of Hub::sensorTypes
-- | -- | -- | --
mihome.0 | 2018-11-03 03:33:11.337 | warn | Could not add new sensor: Type "sensor_magnet" is not valid, use one of Hub::sensorTypes
mihome.0 | 2018-11-03 03:33:09.640 | warn | Could not add new sensor: Type "acpartner.v3" is not valid, use one of Hub::sensorTypes
mihome.0 | 2018-11-03 03:33:09.531 | info | Change connection status: false
mihome.0 | 2018-11-03 03:33:09.494 | info | starting. Version 1.2.3 in /opt/iobroker/node_modules/iobroker.mihome, node: v8.11.1
mihome.0 | 2018-11-03 03:33:09.436 | info | States connected to redis: 127.0.0.1:6379
mihome.0 | 2018-11-03 03:33:09.427 | debug | statesDB connected
mihome.0 | 2018-11-03 03:33:09.384 | debug | objectDB connected
mihome.0 | 2018-11-03 03:33:05.686 | info | terminating

**Comment by DoraDeu** [comment]
Die Integration dieses Gateways würde ich auch sehr begrüßen.

**Comment by JvB94** [comment]
PUSH - ist damit zu rechnen das dazu etwas kommt? Würde mich wahnsinnig freuen.
