### ISSUE TITLE
Alarm scharf/unscharf schalten über iobroker

### ISSUE THREAD

**Issue by abuzzeberlin** [ioBroker/ioBroker.mihome#53]
Hallo
Gibt es eine Möglichkeit den Alarm vom Xiaomi Gateway über iobroker zu schalten ?
Bis jetzt bekomme ich den Alarm aktiviert / deaktiviert über die Mi Home App.
Oder ist das in der API nicht vorgesehen?

**Comment by GermanBluefox** [comment]
Leider mihome gateway gibt die Einstellungen nicht nach außen.
