### ISSUE TITLE
keine verbindung zu mihome

### ISSUE THREAD

**Issue by xDarix** [ioBroker/ioBroker.mihome#56]
Hi ich bekomme meine mihome instanz nicht zum laufen. Die Statusanzeige ist immer gelb. (Verbunden mit mihome: falsch)
Die IP und den Key habe ich korrekt eingegeben und und die freigebe in der App aktiviert. 
Region ist auf Mainland China eingestellt.
Der log zeigt nur die beiden meldungen.

mihome.0 | 2018-12-13 18:36:21.360 | info | Change connection status: false
mihome.0 | 2018-12-13 18:36:21.186 | info | starting. Version 1.2.3 in /opt/iobroker/node_modules/iobroker.mihome, node: v10.13.0

Gruß
Dari

**Comment by Hypnos3** [comment]
Ich habe selbes Problem.

**Comment by GermanBluefox** [comment]
Dann muss man dann den Traffik mit Wireshark aufzeichnen und analysieren

**Comment by Fr3dler** [comment]
Hallo ich habe bei mir das gleiche Problem und auch schon allerhand versucht...
Heute mal mit wireshark versucht --> es ist allerdings kaum traffik da!!

einmal über den port 9898 - hier gibt es einen eintrag wenn man den mihome adapter startet / neustartet... sonst kommt hier nichts..
![image](https://user-images.githubusercontent.com/44732996/51137987-466c7f80-1840-11e9-9df8-822cb0295aa6.png)

und über die ip des gateway -> hier 10.10.0.71
iobroker läuft hier auf -> 10.10.0.2

ich habe einen ping versucht.. sieht man..
das gateway wurde neu gestartet..
und ich habe über die App auf dem Handy (hier 10.10.0.132) das licht aktiviert und in den Einstellungen den "wireless protocoll adapter" deaktiviert und wieder aktiviert..

![image](https://user-images.githubusercontent.com/44732996/51138121-90556580-1840-11e9-9512-5adfd468a1c8.png)

Wenn hier etwas interessantes dabei ist kann ich dir noch Details schicken..

Gruß
Fridi

**Comment by Hypnos3** [comment]
Ich habe mittlerweile herausgefunden, daß es vom Mi Gateway verschiedene Versionen gibt. Mit der Version 3 hat Xiaomi das Protokoll geändert und daher geht es nicht mehr.

**Comment by Gieskanne** [comment]
I know also two persons with the same issue.
By the way, the new gateway is now Homekit compatible, maybe that helps finding a new way to communicate with the Gateway v3.

**Comment by MBeeken73** [comment]
Bei mir funktioniert es leider auch nicht!
Gibt es schon eine Lösung für die V3?

**Comment by Fr3dler** [comment]
Diese Lösung hat bei mir funktioniert:
https://forum.iobroker.net/topic/19115/xiaomi-mi-gateway-v3-workaround-f%C3%BCr-gelben-mihome-adapter
