### ISSUE TITLE
new device: Aqara curtain motor

### ISSUE THREAD

**Issue by greynoO** [ioBroker/ioBroker.mihome#57]
I would like to control the Aqara curtain motor. Can this be added?

**Comment by GermanBluefox** [comment]
Is it Wi-Fi or zigbee device?

пт, 14 дек. 2018 г., 17:45 greynoO notifications@github.com:

**Comment by greynoO** [comment]
zigbee! 
Same line as the current Aqara sensors. It is recognized as "lumi.curtain" after pairing..

**Comment by greynoO** [comment]
sorry wrong repo! I meant to post this in the repo for ioBroker.zigbee, my bad!
