### ISSUE TITLE
Xiaomi WXKG02LM Aqara Smart Light Switch Wireless

### ISSUE THREAD

**Issue by wowik2018** [ioBroker/ioBroker.mihome#58]
Es wird nicht der lange klick bei den eckigen Kabellosen Schalter unterstützen.

mihome.0 | 2018-11-20 18: 44: 44.477 | debuggen | RAW: {"cmd": "report", "model": "remote.b286acn01", "sid": "158d0002829c5c", "short_id": 37, "data": {"channel_0": "long_click"}}
-- | -- | -- | --

**Comment by wowik2018** [comment]
mihome.0 | 2018-12-18 20:08:42.541 | debug | RAW: {"cmd":"report","model":"remote.b286acn01","sid":"158d0002829c5c","short_id":37,"data":{"channel_1":"long_click"}}
-- | -- | -- | --

**Comment by wowik2018** [comment]
Не кто не поможет?

**Comment by DocGame69** [comment]
Wenn dies unterstützt werden würde, wäre es ein "Hammer-Feature". Ich habe zig Teile verbaut und hätte einige Blockly-Ideen. Gerade bei Rolladensteuerung wäre es fantastisch.....

**Comment by wowik2018** [comment]
Bitte schreiben Sie ein Antwort, ob dass geht oder nicht!!!

**Comment by solarsnoop** [comment]
Aqura wireless relais controller 2 channels
Would be great if could add to the iobroker divice list, and can setup to switch with Java script. Would be a great add on feature

**Comment by DocGame69** [comment]
Any news for Long Klick?
`2019-07-03 18:58:36.349  - [34mdebug[39m: mihome.0 data: 158d00028f7b08(remote.b186acn01): {"channel_0_double":false,"channel_0_long":true,"channel_0":false}
2019-07-03 18:58:36.352  - [34mdebug[39m: mihome.0 RAW: {"cmd":"report","model":"remote.b186acn01","sid":"158d00028f7b08","short_id":3483,"data":{"channel_0":"long_click"}}
2019-07-03 18:58:36.652  - [34mdebug[39m: mihome.0 data: 158d00028f7b08(remote.b186acn01): {"channel_0_long":false}`

This and the LongKlick and DoubleKlick on the 2 Button Switch was great.
With my Deconz-Adapter this Feature works fine, but MiHomeHub work more stable.

Sorry for my Bad Englisch

Greetings DocGame69
