### ISSUE TITLE
Einbindung Yeelight bulbs

### ISSUE THREAD

**Issue by zwickolino** [ioBroker/ioBroker.mihome#6]
Hallo allerseits!

Zunächst Hut ab und Danke an euch Fachleute.

Ist aus eurer Sicht auch eine Unterstützung der Yeelight Wifi-Leuchten (E27) machbar?

Als Laie stehe ich vor dem Problem aktuell eine Alexa-Einbindung von Yeelights nur unter Nutzung des Singapur-Servers zu realisieren. Dann bekomme ich aber den Gateway (da Mainland China notwendig) insgesamt nicht installiert. 

Wäre klasse wenn ihr die noch aufnehmen könntet!

**Comment by jangatzke** [comment]
Das ist machbar, hat aber nichts mit mihome zu tun. Der mihome Adapter bindet das mihome Gateway an. Die Yeelight Leuchten arbeiten direkt mit Wifi. Entsprechend ist ein eigener adapter nötig. Es gibt im Forum schon eine Script-Lösung.

**Comment by zwickolino** [comment]
Ok, Danke für die Info... Dann suche ich nochmal nach der Skript Variante.
Ich dachte da die Einbindung auch über die Mi Home App erfolgt,
man könnte die Yeelight‘s ggf. einfach mit reinnehmen. Denkfehler...
Ich hatte da u.a. wegen der Server-Thematik China/Mainland (Gateway) vs. Singapur (Yeelight)
dran gedacht, das es so einfacher wäre.
