### ISSUE TITLE
Ikea Tradfri support

### ISSUE THREAD

**Issue by Tousakusha** [ioBroker/ioBroker.mihome#64]
Is it possible to add IKEA Tradfri support? The Bulbs can be added via app but are seemingly not supported in iobroker.

**Comment by limesteve81** [comment]
+1 Yes, please. That would be great !

**Comment by LosPimpos** [comment]
+1...schließe mich an, wäre echt toll wenn man die Ikea tradfri im Adapter sehen könnte.

**Comment by Apollon77** [comment]
Why you do not use the tradfri adapter?

**Comment by LosPimpos** [comment]
because i/we don't have the tradfri gateway :)

**Comment by Tousakusha** [comment]
Because:
1 - all those ikea gateways keep crashing on me and ate unreliable this way
2 - i still would need the xiaomi gateway.
And since the gateway supports ikea bulbs now, it would be great to have them included in the adapter
