### ISSUE TITLE
Aqara Gateway support

### ISSUE THREAD

**Issue by allesclip** [ioBroker/ioBroker.mihome#65]
Ist es möglich das Aqara Gateway zu unterstützen? Das Gateway welches Homekitunterstützung hat.

**Comment by MickL** [comment]
Maybe if you write in english everyone in the world could help you on this international platform

**Comment by Apollon77** [comment]
We allow German and English here because a lot of people especially in Germany do not speak that well English. 

Did you tried the mihome and such Adapters that already focus on Xiaomi devices?!

**Comment by Apollon77** [comment]
Ps: hast du schonmal den mihome Adapter bzw die anderen Adapter versucht die sich auf Xiaomi Geräte spezialisiert haben?

**Comment by honk95** [comment]
Are there any news to this? / Gibt es hierzu irgendwelche Neuigkeiten?
Ich habe mal ein wenig auf der Aqara Seite gestöbert und einiges in Richtung LAN Protokoll gefunden und auch zu ner API. Bisher gibt es für mich aber nicht die Möglichkeit wie beim Mijia Gateway in der Mi Home App da irgendetwas zu aktivieren. Habe sowohl das Mijia als auch das Aqara Gateway in Chinesischer Version und wäre eigentlich ganz gerne auf das EU Aqara Gateway umgestiegen, jedoch nicht ohne LAN Kommunikation / ioBroker Kommunikation

>> http://docs.opencloud.aqara.com/development/gateway-LAN-communication/
>> https://opencloud.aqara.com/?lang=en
