### ISSUE TITLE
Issue: connection state for gateway

### ISSUE THREAD

**Issue by grdminer** [ioBroker/ioBroker.mihome#66]
Dear Team, Dear GermanBlueFox

realeted to #16 

last year i've asked for a connection state indicator for gateways. It's already builtin now, thanks a lot. But unfortunately it shows almost always false. I'm using 3 gateways and all are online and can be used (light on/off, different colors etc.) by changing states of corresponding entries in iobroker object tab but connection status is still false. I've checked the log and iobroker receives frequent heartbeats of all gateways. Any idea?

German:
Letztes Jahr habe ich hier nach einem Connection Indikator für die Gatways gefragt und Du/ihr habt ihn eingebaut, Vielen Dank nochmal dafür. Ich verwende 3 Gateways und die Indikatoren zeigen fast immer den Zustand false an. Selbst wenn ich direkt über die objekte und states in iobroker die Gateways verwende (Licht, Ton etc.) bleibt der Indikator auf false. Im Log kann ich sehen das von alle Gateways hearbeats empfangen werden. Was mache ich falsch?

Vielen Dank und Viele Grüße
GRDMINER

**Comment by Ilovegym66** [comment]
here the same, I've 4 Gateways, there are working fine, and are connected, but the state is everytime "false" .

**Comment by martinschm** [comment]
Same here with my 2 gateways. Maybe the state indicator got mixed up.

**Comment by grdminer** [comment]
Dear Team,

any news on this topic?

Best regards
