### ISSUE TITLE
integration of Xiaomi Aqara smart LED bulb (ZNLDP12LM)

### ISSUE THREAD

**Issue by ltsalvatore** [ioBroker/ioBroker.mihome#71]
hey guys, 

any chance to get **Xiaomi Aqara smart LED bulb (ZNLDP12LM)** implemented into the mihome adapter in order to use with iobroker?

**Comment by LosPimpos** [comment]
+ 1 , please implement the bulb...

**Comment by TodiDives** [comment]
Yes,please. It will be nice

**Comment by ltsalvatore** [comment]
hi guys.. 
any chance of this being realized in the near future?

im not a programmer at all, but if i can help in any other way in order to speed this up, please let me know

**Comment by Gieskanne** [comment]
Same issue as #54 , but in the older one is actually a log output which could help to add this device.
