### ISSUE TITLE
Duplicate xiaomi gateway in objects tree

### ISSUE THREAD

**Issue by save2love** [ioBroker/ioBroker.mihome#72]
After searching devices via mihome adapter it appears two gateways instead of one. One with leading zero and one without. The data separates between these gateway objects and updates randomly (in the first one or another one).
If I delete one how I can be sure that the data is actual.
What's wrong with identifing gateways?
![image](https://user-images.githubusercontent.com/617936/54357371-99a75680-4666-11e9-91d9-53d2011968e2.png)

![image](https://user-images.githubusercontent.com/617936/54356177-a4acb780-4663-11e9-8efe-c635301ca8c5.png)

**UPD 2019-03-14**
Logs:
```
RAW: {"cmd":"iam","port":"9898","sid":"04cf8c915f95","model":"gateway","proto_version":"1.1.2","ip":"192.168.0.11"}
...
RAW: {"cmd":"read_ack","model":"gateway","sid":"4cf8c915f95","short_id":0,"data":{"rgb":0,"illumination":276,"proto_version":"1.1.2"}}
```
As you can see sometimes sid is 4cf8c915f95 and sometimes 04cf8c915f95 and it cause duplicating gateways because they are look like two different devices in the system

ioBroker version: 3.6.0
MiHome adapter version: 1.2.5

**Comment by Ilovegym66** [comment]
here the same, js-controller 1.5.7, admin 3.6.0, MiHome 1.2.5, Node 8.15.1, NPM 6.4.1 
I can delete the directory of the double gateway, but after a time it's created again..

**Comment by save2love** [comment]
I found the same issue with Xiaomi Gateway in [Home-Assistant's issues list](https://github.com/home-assistant/home-assistant/issues/21418)
The solution is add missing leading zero of the gateway mac address.
Need to try!

**Comment by save2love** [comment]
@Ilovegym66 Please try my last commit https://github.com/save2love/ioBroker.mihome/commit/748370e29b5ee3a6545166710c2cc8064944fd00
It can help you.

**Comment by DirtyAtze** [comment]
I have the same Issue on 2 of my gantways. Will this be fixed in a future Update or do i have to use a workaround?
Is thr solution for home-assistant working for ioBroker? Where can i find the .py File?
