### ISSUE TITLE
Xiaomi Video Klingel

### ISSUE THREAD

**Issue by SchimmerMediaHD** [ioBroker/ioBroker.mihome#75]
Hey Leute, 

Da die Video Tür Klingel von Xiaomi auch über die Mi Home App eingerichtet wird, würde ich es cool finden wenn ich zum beispiel den Bewegungssensor der Klingel auch im ioBroker abgreifen könnte um damit etwas triggern zu können, oder natürlich auch das Bild um es zum bespiel in VIS oder Telegram weiter verwenden zu können :)

Hier ein paar nähere Details und ein Video von mir über die Klingel...
https://dealheros.de/produkt/xiaomi-smarthome-video-tuerklingel-720p-ir-nachtsicht-%E2%9C%AA/

Liebe Grüße, 

Dennis

**Comment by mackedanz** [comment]
Das wäre eine feine Sache, wäre schön wenn es umgesetzt werden könnte

**Comment by Meraluna** [comment]
und ob man das Braucht würde mich super freuen über ne coole API :)

**Comment by RamsesIoBroker** [comment]
We need it !!!

**Comment by smartmood** [comment]
Jaaa ich kann @SchimmerMediaHD  nur zustimmen! Bitte umsetzen

**Comment by Master6726** [comment]
Bin auch dafür :-)

**Comment by grillmeister1** [comment]
I need urgently.
Bitte umsetzten.

**Comment by mistermaster2punkt0** [comment]
Ich kann mich nur anschließen: Es wäre super, wenn eine Einbindung möglich wäre.

**Comment by SchimmerMediaHD** [comment]
am besten Teilt Ihr alle nochmal den Beitrag damit er mehr Beachtung findet und diejenigen unter euch die hier schon kommentiert haben das sie auch für solch eine Einbindung sind, sollten meinen Hauptbeitrag mit einem Daumen versehen, damit dieser eben entsprechend Beachtung findet :)

**Comment by grillmeister1** [comment]
Hat schon wer Fortschritte erzielt oder geht es sogar schon?

**Comment by Ilovegym66** [comment]
wer hat denn eine im Einsatz und kann ein Logfile liefern? Abgesehen davon, dass ein "einrichten in der App" nicht bedeutet, dass es mit dem MiHome Adapter ueberhaupt auszuwerten ist. Kommt auf das Protokoll an, wenn die Klingel miio 2.0 nutzt, wird der mio-adapter benoetigt und hier waere das falsch.

**Comment by smartmood** [comment]
@Ilovegym66 
Ich habe eine im Einsatz und könnte sogar eine zur Verfügung stellen falls das noch erforderlich ist?
Hat schon jemand das Logfile geliefert?
LG

**Comment by grillmeister1** [comment]
Ich habe noch keine und kann leider das logfile nicht liefern.

**Comment by smartmood** [comment]
@Ilovegym66 
Wenn du mir verrätst wie ich an das Logfile komme, lasse ich es dir gerne zukommen :)

**Comment by Ilovegym66** [comment]
in iobroker auf Instanzen, Expertenansicht, Logstufe auf Debug stellen. Dann an der Klingel mal rumspielen, dann das Logfile von /opt/iobroker/log/iobroker.datum.log mit "less iobroker.2019-08-07.log | grep mihome" filtern und hier hochladen. Dann wissen wir, ob die Klingel ueberhaupt was ueber den mihome adapter schickt, ich denke eher nicht, die verwendet wahrscheinlich das miio2.0 protokoll, dafuer gibts n anderen adapter. Aber abwarten.

**Comment by smartmood** [comment]
@Ilovegym66 
aktuell läuft bei mir leider der Mi Home Adapter nicht, weil ich den Port öffnen muss - dies werde ich aber nun machen. Sobald der Adapter läuft werde ich das mal probieren.

**Comment by grillmeister1** [comment]
Schön dass Ihr an der Sache dran seit. Bin gespannt wie’s ausgeht.

**Comment by SchimmerMediaHD** [comment]
@lovegym66 Welchen anderen Adapter gibt's denn wo wir eventuell Signale von der Klingel bekommen?

**Comment by Ilovegym66** [comment]
Hi, es gibt mindestens 2 Varianten, einmal den MiHome Adapter hier, und einmal den mioo adapter, der viele andere Geraete unterstuetzt, die ueber das miioo Protokoll laufen. 
Es kann der mioo Adapter problemlos dazu installiert werden. 

Adapter auf Debug stellen, ganz wichtig, dann ein paarmal auf die klingel druecken, wenn wir Glueck haben, ist was im Protokoll zu sehen, ansonsten hilft nur ein Auszug mit Wireshark.

Ich hatte mir vor ein paar Monaten so ne billige China Videoklingel geholt, dachte ich koennte da wenigstens den Videostream oder n Signal abgreifen, aber die sendet alles verschluesselt ueber UDP mit rolling Ports... keine Chance.. schon doof, wenn die Sicherheit so gut ist.. :-)

**Comment by grillmeister1** [comment]
@lovegym66
den mioo adapter kann ich nicht finden.
der mihome adapter wird nicht grün da ich auch keinen key habe. auf debug kann ich ihn stellen.
Was kann ich machen (habe keine Xiaomi Gateway)
Würde dir gerne das Protokoll schicken.

**Comment by Ilovegym66** [comment]
wenn die Klingel nicht am Gateway eingebunden wird, kann hier der Adapter nix machen, da ein Gateway zwingend da sein muss. Dann beim mioo Adapter ein Issue erstellen.
https://github.com/smarthomefans/ioBroker.miio

**Comment by smartmood** [comment]
@Ilovegym66 
Soo ich habe es gerade endlich mal geschafft im Protokoll nach  "less iobroker.2019-08-07.log | grep mihome" zu suchen - wird aber nichts gefunden... 
Habe mir nun den miio Adapter installiert. Was genau muss ich nun eingeben?
Wie finde ich die IP Adresse der Klingel raus?

**Comment by grillmeister1** [comment]
Das ist gut sonst hätte ich demnächst geschaut. 
Die ip findest du im Router. Name müsste sein DLing-DoorBell.

**Comment by Ilovegym66** [comment]
Das issue hier ist im falschen Adapter, bitte schliessen.

**Comment by SchimmerMediaHD** [comment]
Kann man es dann nicht irgendwie verschieben, wir wünschen uns irgendwie einen Adapter dazu, wäre so cool wenn da jemand einen Plan hätte wie man das hinbekommen könnte

**Comment by Ilovegym66** [comment]
was willst du denn verschieben, hier steht absolut  nix wissenswertes ... ausser, dass zwei Leute das Teil haben..  
Zum debuggen braucht man zumindest mehr Informationen, Ports, Protokoll, Datenverkehr.. also wireshark anwerfen und mitschneiden und auswerten. Aber hier der Adapter kann nur devices, die über das Gateway gehen.

**Comment by grillmeister1** [comment]
https://github.com/smarthomefans/ioBroker.miio/issues/21

Hab mir erlaubt in dem anderen Adapter zu posten. Bitte folgt alle um die Anbindung voran zu treiben.
