### ISSUE TITLE
Change connection status on timeout

### ISSUE THREAD

**Issue by Elr0n** [ioBroker/ioBroker.mihome#76]
Hi,

it seems, version 1.2.6 of this adapter is causing some connection problems with Xiaomi Gateways. Effects you can observe:

- The Adpater "traffic light" continuously switches between green and orange (every timeout seconds)
- In the Log you see "info" entries like follows
```
mihome.0	2019-05-07 12:33:53.612	info	Change connection status: true
mihome.0	2019-05-07 12:33:23.537	info	Change connection status on timeout after 20000ms: false
```
- The Gateway does not react on commands (e.g. turn on lights)
- Connected sensors are partly not responding

When you downgrade to version 1.2.5 as follows, the problem is gone

```
cd /opt/iobroker
iobroker stop
npm install iobroker.mihome@1.2.5 --production
iobroker upload mihome
iobroker start
```

If you upgrade again to 1.2.6, the problem is back.

**Comment by limesteve81** [comment]
Hi,

I have the same issue, the adapter switches between green and yellow. Same error after timeouts.
While the adapter is green, I have full connection to my system. While it is yellow, there is no communication.

I don't remember of any changes neither the gateway nor the app or iobroker / adapter.

Curiously it appears in 1.2.5 an every other version (including 1.2.6 and lower).

What could that be?

**Comment by limesteve81** [comment]
Okay, I remember what I did and haven't think that this could cause a difference:
I put the iobroker (Raspi) to another place. Now replaced to the original spot, everything works again.
