### ISSUE TITLE
Why some sensors class fixed type value?

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.mihome#80]
Hi all

I think we need fix all sensor classes which fixed type value.
Gateway, Button, Curtain, DoorSensor, Lock, Plug, WaterSensor classes fixed type value to gateway, switch, curtain, magnet, lock_aq1, plug, sensor_wleak.aq1.

This type value are used in:
device channel name.
device channel icon.
send write command.

This sheet collect all data you need to check
https://docs.google.com/spreadsheets/d/1O7ZW8EgJecnw0eZ2siUmD-UFUU0pxYkdikrOpNX1wTA/edit?usp=sharing

I think we need set sensor class's type value based on model. Because device report, heartbeat, write commands all contains model value.
And for 86plug, sensor_switch.aq2 or some model like those may meet issue when send write command. Because in protocol description,
```json
{
"cmd":"write",
"model":"86plug",
"sid":"123456",
....
}
```
model value is device model value, not fixed type. 

Why I need discuss.

Because is type value is set by model, device channel name will change. This will cause some incompatible issue for user who are using those device.

**Comment by SchumyHao** [comment]
If you agree with change type by device model.
I think I can add an independent variable to store current fixed type value. And use this new variable to set device channel name. This can make adapter compatible with old version

**Comment by GermanBluefox** [comment]
I find it OK.

**Comment by SchumyHao** [comment]
Write command will be affected.
For now, only 86plug will be affacted.

With more and more devices model will be added, we should follow protocol to control device, I think.

And device icon is affected.

So I think we should make this uniform:
- All sensor class need save device model info in sensor instant.
- Use this info to set device icon. 
- Use this info when send write command(follow protocol design).
- It's fine we can use `sensor class name + sid` as channel ID, can make channel id shorter.

**Comment by SchumyHao** [comment]
PR created in #81
