### ISSUE TITLE
Support for "Smartmi Evaporative Humidifier"

### ISSUE THREAD

**Issue by adieball** [ioBroker/ioBroker.mihome#83]
Dieser SmartMI Luftbefeuchtern wird ja über die mi-Home App unterstützt. 
Im Iobroker taucht er aber nicht auf.

Kann ich was dazu beitragen dass der unterstützt wird?

**Comment by Ilovegym66** [comment]
schau mal ob einer der beiden Adapter bei dir damit geht:
https://github.com/JoJ123/ioBroker.mihome-airpurifier

oder der hier:
https://github.com/SchumyHao/ioBroker.miio

Die Luftreiniger sind zwar in der App, laufen aber über ein anderes protokoll. Der MiHome-Adapter unterstützt nur Geräte/Sensoren, die über das Gateway angemeldet werden. Eigentlich ist der Name des Adapters falsch, sollte eher Xiaomi-Gateway heissen.. :-)

**Comment by adieball** [comment]
Hi

Der Luftreiniger ist über das Gateway angemeldet. 

Von meinem iPhone gesendet

**Comment by Ilovegym66** [comment]
sorry, muss dir widersprechen, das ist ein Wifi Device und wird über das mioo protokoll gesteuert, die Gateways können nur Zigbee (deshalb heisst es ja Gateway).  Von daher hier falscher Ort, öffne bitte ein issue beim mioo adapter oder purifyer adapter. Wenn du in der App auf ein Gateway gehst und möchtest ein Device adden, dann ist auch so ein Gerät gar nicht dabei. 
Was der aber kann: Er ist selbst ein Bluetooth-Gateway, d.h. mit dem kannst du deine Xiaomi Flower Sensoren oder sonstige Bluetooth Devices ins Wlan holen, ohne mit dem Handy und der App in der Nähe zu sein.  Mehr hier zu lesen:
https://de.gearbest.com/air-purifier/pp_1650027.html

**Comment by adieball** [comment]
OK, über welches Protokoll es gesteuert wird, weiss ich nicht, aber ich habe es nur über das Gateway angemeldet, so wie andere Sensoren / Aktoren auch.
Könnte es sein, dass eine neuere Version auf dem Gateway seine eigene WLAN Verbindung dazu benutzt auch mir WiFi Geräten zu kommunizieren?


![IMG_2694](https://user-images.githubusercontent.com/6988389/59120411-9cf46a80-8955-11e9-94cf-d8dd8a65c88a.png)
![IMG_2695](https://user-images.githubusercontent.com/6988389/59120412-9cf46a80-8955-11e9-86ba-ed70b532a93a.png)
![IMG_2696](https://user-images.githubusercontent.com/6988389/59120413-9d8d0100-8955-11e9-8ab5-e0791316886c.jpeg)

**Comment by Ilovegym66** [comment]
Hi, nee, das Gerät ist nur über die App im WLAN und nicht mit dem Gateway verbunden. Schau Mal bitte direkt im Gateway nach ( also in der App auf das Gateway klicken, dann auf der neuen Seite auf Geräte, da siehste alle Sensoren, die mit dem Gateway verbunden sind. Ich Wette, der smartmi ist da nicht dabei.. 😉??

**Comment by adieball** [comment]
Recht hast du. 
Die anderen vorgeschlagenen Adapter können das Teil aber auch noch nicht .... naja, dann warte ich halt. 

Danke



Von meinem iPhone gesendet

**Comment by Ilovegym66** [comment]
hab n Issue da aufgemacht, wo ich denke, dass es hingehört, hoffe, der Programmierer liest es und hat auch Zeit...
