### ISSUE TITLE
Xiaomi Aqara Two-way control module Wireless Relay Controller 2 channels

### ISSUE THREAD

**Issue by solarsnoop** [ioBroker/ioBroker.mihome#84]
Hi, would be great if you could add this relay for support in your iobroker app. This would make it easy to controll this relais also by java scripts.

**Comment by algar42** [comment]
Agree.. Very need :)

**Comment by algar42** [comment]
Tried to add Relay to adapter, but for some reasons it returns empty model:
{"cmd":"read_ack","model":"","sid":"158d0003553c74","short_id":40835,"data":"{\"voltage\":3600}"}

Any idea why the model can be empty?

**Comment by algar42** [comment]
in v1.3.0 it is now possible to add relay using device SID. See https://github.com/ioBroker/ioBroker.mihome#add-device-by-sid
