### ISSUE TITLE
Adapter not support PM2.5 wifi sensor

### ISSUE THREAD

**Issue by VovkaSOL** [ioBroker/ioBroker.mihome#89]
![Без названия](https://user-images.githubusercontent.com/52788297/61053213-cccfdb80-a3f5-11e9-8a49-76fda4e612d7.jpg)
Hi friends, xiaomi adapter not support PM2.5 wifi sensor, please add it.

**Comment by VovkaSOL** [comment]
May help https://github.com/aholstenson/miio/issues/38

**Comment by Ilovegym66** [comment]
looks like the device uses the miio protocoll, there are two additional adapters for iobroker:
https://github.com/SchumyHao/ioBroker.miio
and
https://github.com/kirovilya/ioBroker.miio
