### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by mic1970** [ioBroker/ioBroker.mihome#9]
Hallo,

ich habe ein Problem beim Einrichten des Adapters. Ich bekomme den Gateway bzw. den Adapter nicht zum laufen. Der Gateway funktioniert unter der Mi HOME APP und wurde auch so eingestellt wie hier beschrieben. Anbei die Fehlermeldungen aus dem LOG vom iobroker:

host.iobroker | 2018-01-16 18:28:33.556 | error | instance system.adapter.mihome.0 terminated with code 0 (OK)
-- | -- | -- | --
mihome.0 | 2018-01-16 18:28:33.539 | info | terminating
mihome.0 | 2018-01-16 18:28:33.516 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
mihome.0 | 2018-01-16 18:28:33.516 | error | at Manager.Emitter.emit  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
mihome.0 | 2018-01-16 18:28:33.516 | error | at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
mihome.0 | 2018-01-16 18:28:33.516 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
mihome.0 | 2018-01-16 18:28:33.516 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
mihome.0 | 2018-01-16 18:28:33.516 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1346:35)
mihome.0 | 2018-01-16 18:28:33.516 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1458:21
mihome.0 | 2018-01-16 18:28:33.516 | error | at /opt/iobroker/node_modules/iobroker.mihome/main.js:1055:21
mihome.0 | 2018-01-16 18:28:33.516 | error | at startMihome (/opt/iobroker/node_modules/iobroker.mihome/main.js:1104:11)
mihome.0 | 2018-01-16 18:28:33.516 | error | at new Hub (/opt/iobroker/node_modules/iobroker.mihome/lib/mihome/Hub.js:31:20)
mihome.0 | 2018-01-16 18:28:33.516 | error | TypeError: function from() { [native code] } is not a constructor
mihome.0 | 2018-01-16 18:28:33.510 | error | uncaught exception: function from() { [native code] } is not a constructor
mihome.0 | 2018-01-16 18:28:33.498 | error | no key defined. Only read is possible
mihome.0 | 2018-01-16 18:28:33.391 | info | starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.mihome, node: v4.2.6
host.iobroker | 2018-01-16 18:28:32.349 | info | instance system.adapter.mihome.0 started with pid 2236

Danke für die Mühe.

Viele Grüße
Michael

**Comment by Apollon77** [comment]
Bitte mal die GitHub-Version installieren. Fehler immer noch der gleiche?

**Comment by mic1970** [comment]
Habe ich gemacht. Adapter deinstalliert und Github Version installiert. Der Fehler bleibt der Gleiche.

**Comment by Apollon77** [comment]
Exakt?AUch alle Zeilennummern und so?

**Comment by mic1970** [comment]
Hier mal der Auszug aus dem Log. Für mich sieht es so aus.


host.iobroker | 2018-01-16 20:57:27.840 | error | instance system.adapter.mihome.0 terminated with code 0 (OK)
-- | -- | -- | --
mihome.0 | 2018-01-16 20:57:27.795 | info | terminating
mihome.0 | 2018-01-16 20:57:27.768 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
mihome.0 | 2018-01-16 20:57:27.768 | error | at Manager.Emitter.emit  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
mihome.0 | 2018-01-16 20:57:27.768 | error | at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
mihome.0 | 2018-01-16 20:57:27.768 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
mihome.0 | 2018-01-16 20:57:27.768 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
mihome.0 | 2018-01-16 20:57:27.768 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1346:35)
mihome.0 | 2018-01-16 20:57:27.768 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1458:21
mihome.0 | 2018-01-16 20:57:27.768 | error | at /opt/iobroker/node_modules/iobroker.mihome/main.js:1055:21
mihome.0 | 2018-01-16 20:57:27.768 | error | at startMihome (/opt/iobroker/node_modules/iobroker.mihome/main.js:1104:11)
mihome.0 | 2018-01-16 20:57:27.768 | error | at new Hub (/opt/iobroker/node_modules/iobroker.mihome/lib/mihome/Hub.js:31:20)
mihome.0 | 2018-01-16 20:57:27.768 | error | TypeError: function from() { [native code] } is not a constructor
mihome.0 | 2018-01-16 20:57:27.762 | error | uncaught exception: function from() { [native code] } is not a constructor
mihome.0 | 2018-01-16 20:57:27.751 | error | no key defined. Only read is possible
mihome.0 | 2018-01-16 20:57:27.657 | info | starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.mihome, node: v4.2.6
host.iobroker | 2018-01-16 20:57:26.665 | info | instance system.adapter.mihome.0 started with pid 6020

**Comment by mic1970** [comment]
Ich habe im Forum gesehen, dass auch andere diesen Fehler haben.

**Comment by mic1970** [comment]
System ist ein Ubuntu 16.04 LTS als virtuelle Maschine unter Proxmox. Alles andere läuft stabil.

**Comment by mic1970** [comment]
Hallo,

habe das Problem gefunden. Ich habe die node.js händisch auf 6.x aktualisiert. Jetzt läuft der Adapter problemlos. 
Danke für die Hilfe.
