### ISSUE TITLE
How to recognize aqara sensor offline

### ISSUE THREAD

**Issue by railin** [ioBroker/ioBroker.mihome#90]
When a aqara sensor (waterleak sensor) is offline, the MiHome App shows after a short time "Offline".
In iobroker there is no chance to see, that the sensor is not online anymore.
I am using IQontrol for my vis. Is there a chance to show the offline status of the sensor in the vis.
THX Rainer

**Comment by passuff** [comment]
Would be interested in a device status feature too...

**Comment by railin** [comment]
Yes. Device status for Xiaomi sensors would be a nice feature for the Adapter. The gateway already has a wlan connection status (online/offline) that I use to check the connection. For me it would be great to have the possibility to check the connection status of all sensors to the gateway, too. The MiHome App already offers this feature.

**Comment by neo4a** [comment]
+1

**Comment by homecineplexx** [comment]
+1

**Comment by homecineplexx** [comment]
+1

**Comment by Knallix** [comment]
I'm also interested in checking the connection
