### ISSUE TITLE
No connection to gateway control hub

### ISSUE THREAD

**Issue by swissglider** [ioBroker/ioBroker.mihome#96]
Hello all,

since some days I can no longer connect to my mi control hub.
It was everything fine before..

If I read behind the chineese letters, it looks like I have firmware 1.4.1_170 and lumi.gateway.v3-
As sayd it was all running fine till some days ago.

Hope someone can help me.
ioBroker is all uptodate with the newest updates..

Many thanks swissglider

**Comment by homecineplexx** [comment]
I have observed a similar phenomenon. after an indefinite time, my gateway is online= false in the data points  and it is no longer set to true, although I can, for example, the light on / off. only reloading the mihome adapter changes the data point again.
Hub Info:
Version No: 272
Firmware Version: 1.4.1_170
model: lumi.gateway.v3
