### ISSUE TITLE
Values can't be read in blockly script

### ISSUE THREAD

**Issue by Cerunnos75** [ioBroker/ioBroker.mihome#99]
In the Objects view the values can be read.
If I try to add the ID in a blockly script, the values are gone.
![1](https://user-images.githubusercontent.com/57447933/69181522-8ad74480-0b0f-11ea-8230-8c1e76c14eae.jpg)
![2](https://user-images.githubusercontent.com/57447933/69181523-8ad74480-0b0f-11ea-9336-5bd93d242fca.jpg)

**Comment by GermanBluefox** [comment]
This is a problem with javascript, not with mihome
